[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "warframe-damage-calculator"
version = "1.1.0"
description = "Analytic Warframe weapon damage calculator."
requires-python = ">=3.14"

[tool.setuptools.packages.find]
where = ["."]
include = ["warframe_damage_calculator*"]
namespaces = true

[tool.setuptools.package-data]
"warframe_damage_calculator" = ["py.typed"]
"warframe_damage_calculator.database" = ["database.json"]
