from typing import Literal


type PrimaryName = Literal[
    "AX-52",
    "Acceltra",
    "Acceltra Prime",
    "Aeolak",
    "Afentis",
    "Afentis Prime",
    "Alternox",
    "Alternox Prime",
    "Ambassador",
    "Amprex",
    "Arbucep",
    "Arca Plasmor",
    "Argonak",
    "Arquebex",
    "Artax",
    "Artemis Bow",
    "Astilla",
    "Astilla Prime",
    "Attica",
    "Basmu",
    "Battacor",
    "Baza",
    "Baza Prime",
    "Boar",
    "Boar Prime",
    "Boltor",
    "Boltor Prime",
    "Braton",
    "Braton Prime",
    "Braton Vandal",
    "Bubonico",
    "Burston",
    "Burston Prime",
    "Buzlok",
    "Carmine Penta",
    "Catchmoon (Primary)",
    "Cedo",
    "Cedo Prime",
    "Cernos",
    "Cernos Prime",
    "Cinta",
    "Coda Bassocyst",
    "Coda Bubonico",
    "Coda Hema",
    "Coda Sporothrix",
    "Coda Synapse",
    "Convectrix",
    "Corinth",
    "Corinth Prime",
    "Cortege",
    "Corvas",
    "Corvas Prime",
    "Cryotra",
    "Cyngas",
    "Daikyu",
    "Daikyu Prime",
    "Dera",
    "Dera Vandal",
    "Deth Machine Rifle",
    "Deth Machine Rifle Prime",
    "Dex Sybaris",
    "Drakgoon",
    "Dread",
    "Dual Decurion",
    "EFV-5 Jupiter",
    "Enkaus",
    "Evensong",
    "Exergis",
    "Felarx",
    "Ferrox",
    "Fluctus",
    "Flux Rifle",
    "Fulmin",
    "Fulmin Prime",
    "Gaze (Primary)",
    "Glaxion",
    "Glaxion Vandal",
    "Gorgon",
    "Gorgon Wraith",
    "Gotva Prime",
    "Grakata",
    "Grattler",
    "Grinlok",
    "Haalvu",
    "Harpak",
    "Hek",
    "Helstrum",
    "Hema",
    "Higasa",
    "Hind",
    "Ignis",
    "Ignis Wraith",
    "Imperator",
    "Imperator Vandal",
    "Javlok",
    "Karak",
    "Karak Wraith",
    "Kohm",
    "Komorex",
    "Kuva Ayanga",
    "Kuva Bramma",
    "Kuva Chakkhurr",
    "Kuva Drakgoon",
    "Kuva Grattler",
    "Kuva Hek",
    "Kuva Hind",
    "Kuva Karak",
    "Kuva Kohm",
    "Kuva Ogris",
    "Kuva Quartakk",
    "Kuva Sobek",
    "Kuva Tonkor",
    "Kuva Zarr",
    "Lanka",
    "Larkspur",
    "Larkspur Prime",
    "Laser Rifle",
    "Latron",
    "Latron Prime",
    "Latron Wraith",
    "Lenz",
    "Lizzie",
    "MK1-Braton",
    "MK1-Paris",
    "MK1-Strun",
    "Mandonel",
    "Mausolon",
    "Miter",
    "Morgha",
    "Multron",
    "Mutalist Cernos",
    "Mutalist Quanta",
    "Nagantaka",
    "Nagantaka Prime",
    "Nataruk",
    "Neutralizer",
    "Ogris",
    "Opticor",
    "Opticor Vandal",
    "Panthera",
    "Panthera Prime",
    "Paracyst",
    "Paris",
    "Paris Prime",
    "Penta",
    "Perigale",
    "Perigale Prime",
    "Phaedra",
    "Phage",
    "Phantasma",
    "Phantasma Prime",
    "Phenmor",
    "Prime Laser Rifle",
    "Prisma Dual Decurions",
    "Prisma Gorgon",
    "Prisma Grakata",
    "Prisma Grinlok",
    "Prisma Lenz",
    "Prisma Tetra",
    "Proboscis Cernos",
    "Purgator 1",
    "Quanta",
    "Quanta Vandal",
    "Quartakk",
    "Quellor",
    "Rakta Cernos",
    "Rattleguts (Primary)",
    "Rauta",
    "Reconifex",
    "Rubico",
    "Rubico Prime",
    "Sancti Tigris",
    "Scourge",
    "Scourge Prime",
    "Secura Penta",
    "Shedu",
    "Simulor",
    "Snipetron",
    "Snipetron Vandal",
    "Sobek",
    "Soma",
    "Soma Prime",
    "Sporelacer (Primary)",
    "Sporothrix",
    "Stahlta",
    "Steflos",
    "Stinger",
    "Stradavar",
    "Stradavar Prime",
    "Strun",
    "Strun Prime",
    "Strun Wraith",
    "Supra",
    "Supra Vandal",
    "Sweeper",
    "Sweeper Prime",
    "Sybaris",
    "Sybaris Prime",
    "Synapse",
    "Synoid Simulor",
    "Tazicor",
    "Telos Boltor",
    "Tenet Arca Plasmor",
    "Tenet Envoy",
    "Tenet Ferrox",
    "Tenet Flux Rifle",
    "Tenet Glaxion",
    "Tenet Quanta",
    "Tenet Tetra",
    "Tenora",
    "Tenora Prime",
    "Tetra",
    "Thornbak",
    "Tiberon",
    "Tiberon Prime",
    "Tigris",
    "Tigris Prime",
    "Tombfinger (Primary)",
    "Tonkor",
    "Torid",
    "Trumna",
    "Trumna Prime",
    "Vadarya Prime",
    "Vaykor Hek",
    "Vectis",
    "Vectis Prime",
    "Veldt",
    "Velocitus",
    "Verglas",
    "Verglas Prime",
    "Vermisplicer (Primary)",
    "Vinquibus (Primary)",
    "Vulcax",
    "Vulkar",
    "Vulkar Wraith",
    "Vulklok",
    "Zarr",
    "Zenith",
    "Zhuge",
    "Zhuge Prime",
]

type SecondaryName = Literal[
    "Acrid",
    "Aegrit",
    "Afuris",
    "Afuris Prime",
    "Akarius",
    "Akarius Prime",
    "Akbolto",
    "Akbolto Prime",
    "Akbronco",
    "Akbronco Prime",
    "Akjagara",
    "Akjagara Prime",
    "Aklato",
    "Aklex",
    "Aklex Prime",
    "Akmagnus",
    "Akmagnus Prime",
    "Aksomati",
    "Aksomati Prime",
    "Akstiletto",
    "Akstiletto Prime",
    "Akvasto",
    "Akvasto Prime",
    "Akzani",
    "Angstrum",
    "Arca Scisco",
    "Athodai",
    "Athodai Prime",
    "Atomos",
    "Azima",
    "Balefire Charger",
    "Ballistica",
    "Ballistica Prime",
    "Bolto",
    "Brakk",
    "Bronco",
    "Bronco Prime",
    "Burst Laser",
    "Burst Laser Prime",
    "Cantare",
    "Castanas",
    "Catabolyst",
    "Catchmoon (Secondary)",
    "Cestra",
    "Coda Catabolyst",
    "Coda Pox",
    "Coda Tysis",
    "Cyanex",
    "Cycron",
    "Despair",
    "Detron",
    "Dex Furis",
    "Dex Pixia",
    "Dual Cestra",
    "Dual Coda Torxica",
    "Dual Toxocyst",
    "EFV-8 Mars",
    "Embolist",
    "Epitaph",
    "Epitaph Prime",
    "Euphona Prime",
    "Furis",
    "Fusilai",
    "Gammacor",
    "Gaze (Secondary)",
    "Glory",
    "Grimoire",
    "Hikou",
    "Hikou Prime",
    "Hystrix",
    "Hystrix Prime",
    "Knell",
    "Knell Prime",
    "Kohmak",
    "Kompressa",
    "Kompressa Prime",
    "Kraken",
    "Kulstar",
    "Kunai",
    "Kuva Brakk",
    "Kuva Kraken",
    "Kuva Nukor",
    "Kuva Seer",
    "Kuva Twin Stubbas",
    "Laetum",
    "Lato",
    "Lato Prime",
    "Lato Vandal",
    "Lex",
    "Lex Prime",
    "MK1-Furis",
    "MK1-Kunai",
    "Magnus",
    "Magnus Prime",
    "Mara Detron",
    "Marelok",
    "Noctua",
    "Nukor",
    "Ocucor",
    "Onos",
    "Pandero",
    "Pandero Prime",
    "Plinx",
    "Pox",
    "Prisma Angstrum",
    "Prisma Burst Laser",
    "Prisma Twin Gremlins",
    "Pyrana",
    "Pyrana Prime",
    "Quatz",
    "Rakta Ballistica",
    "Rattleguts (Secondary)",
    "Regulators",
    "Riot-848",
    "Sagek Prime",
    "Sancti Castanas",
    "Scyotid",
    "Secura Dual Cestra",
    "Seer",
    "Sepulcrum",
    "Sicarus",
    "Sicarus Prime",
    "Sonicor",
    "Spectra",
    "Spectra Vandal",
    "Spira",
    "Spira Prime",
    "Sporelacer (Secondary)",
    "Staticor",
    "Stubba",
    "Stug",
    "Synoid Gammacor",
    "Talons",
    "Telos Akbolto",
    "Tenet Cycron",
    "Tenet Detron",
    "Tenet Diplos",
    "Tenet Plinx",
    "Tenet Spirex",
    "Tombfinger (Secondary)",
    "Twin Grakatas",
    "Twin Gremlins",
    "Twin Kohmak",
    "Twin Rogga",
    "Twin Vipers",
    "Twin Vipers Wraith",
    "Tysis",
    "Vasto",
    "Vasto Prime",
    "Vaykor Marelok",
    "Velox",
    "Velox Prime",
    "Vermisplicer (Secondary)",
    "Vesper 77",
    "Viper",
    "Viper Wraith",
    "Zakti",
    "Zakti Prime",
    "Zylok",
    "Zylok Prime",
    "Zymos",
]

type MeleeName = Literal[
    "Ack & Brunt",
    "Akaten",
    "Amanata",
    "Amphis",
    "Anku",
    "Ankyros",
    "Ankyros Prime",
    "Arca Titron",
    "Argo & Vel",
    "Arum Spinosa",
    "Atterax",
    "Azothane",
    "Balla",
    "Batoten",
    "Bo",
    "Bo Prime",
    "Boltace",
    "Broken Scepter",
    "Broken War",
    "Cadus",
    "Cassowar",
    "Caustacyst",
    "Ceramic Dagger",
    "Cerata",
    "Ceti Lacera",
    "Cobra & Crane",
    "Cobra & Crane Prime",
    "Coda Caustacyst",
    "Coda Hirudo",
    "Coda Mire",
    "Coda Motovore",
    "Coda Pathocyst",
    "Corufell",
    "Cronus",
    "Cyath",
    "Dakra Prime",
    "Dark Dagger",
    "Dark Split-Sword",
    "Dark Sword",
    "Dehtat",
    "Desert Wind",
    "Destreza",
    "Destreza Prime",
    "Dex Dakra",
    "Dex Nikana",
    "Diwata",
    "Dokrahm",
    "Dorrclave",
    "Dragon Nikana",
    "Dual Cleavers",
    "Dual Ether",
    "Dual Heat Swords",
    "Dual Ichor",
    "Dual Kamas",
    "Dual Kamas Prime",
    "Dual Keres",
    "Dual Keres Prime",
    "Dual Raza",
    "Dual Skana",
    "Dual Viciss",
    "Dual Zoren",
    "Dual Zoren Prime",
    "Edun",
    "Ekhein",
    "Endura",
    "Ether Daggers",
    "Ether Reaper",
    "Ether Sword",
    "Exalted Blade",
    "Exalted Chromatic Blade",
    "Exalted Umbra Blade",
    "Exalted Umbra Chromatic Blade",
    "Falcor",
    "Fang",
    "Fang Prime",
    "Fragor",
    "Fragor Prime",
    "Furax",
    "Furax Wraith",
    "Galariak Prime",
    "Galatine",
    "Galatine Prime",
    "Galvacord",
    "Garuda Prime Talons",
    "Garuda Talons",
    "Gazal Machete",
    "Ghoulsaw",
    "Glaive",
    "Glaive Prime",
    "Gram",
    "Gram Prime",
    "Guandao",
    "Guandao Prime",
    "Gunsen",
    "Gunsen Prime",
    "Halikar",
    "Halikar Wraith",
    "Harmony",
    "Hate",
    "Heat Dagger",
    "Heat Sword",
    "Heliocor",
    "Hespar",
    "Hirudo",
    "Innodem",
    "Iron Staff",
    "Jat Kittag",
    "Jat Kusar",
    "Jaw Sword",
    "Kama",
    "Karyst",
    "Karyst Prime",
    "Keratinos",
    "Kesheg",
    "Kestrel",
    "Kestrel Prime",
    "Kogake",
    "Kogake Prime",
    "Korrudo",
    "Korumm",
    "Kreska",
    "Krohkur",
    "Kronen",
    "Kronen Prime",
    "Kronsh",
    "Kuva Ghoulsaw",
    "Kuva Shildeg",
    "Lacera",
    "Lacerten",
    "Landslide Fists",
    "Lecta",
    "Lesion",
    "MK1-Bo",
    "MK1-Furax",
    "Machete",
    "Machete Wraith",
    "Magistar",
    "Masseter",
    "Masseter Prime",
    "Mewan",
    "Mios",
    "Mire",
    "Nami Skyla",
    "Nami Skyla Prime",
    "Nami Solo",
    "Nepheri",
    "Nikana",
    "Nikana Prime",
    "Ninkondi",
    "Ninkondi Prime",
    "Obex",
    "Ohma",
    "Okina",
    "Okina Prime",
    "Ooltha",
    "Orthos",
    "Orthos Prime",
    "Orvius",
    "Pangolin Prime",
    "Pangolin Sword",
    "Paracesis",
    "Pathocyst",
    "Pennant",
    "Plague Keewar",
    "Plague Kripath",
    "Plasma Sword",
    "Praedos",
    "Pride",
    "Prisma Dual Cleavers",
    "Prisma Machete",
    "Prisma Obex",
    "Prisma Ohma",
    "Prisma Skana",
    "Prova",
    "Prova Vandal",
    "Pulmonars",
    "Pupacyst",
    "Quassus",
    "Quassus Prime",
    "Rabvee",
    "Rakta Dark Dagger",
    "Reaper Prime",
    "Redeemer",
    "Redeemer Prime",
    "Ripkas",
    "Rumblejack",
    "Ruvox",
    "Sampotes",
    "Sancti Magistar",
    "Sarofang",
    "Sarofang Prime",
    "Sarpa",
    "Scindo",
    "Scindo Prime",
    "Scoliac",
    "Secura Lecta",
    "Sepfahn",
    "Serro",
    "Shadow Claws",
    "Shadow Clones",
    "Shaku",
    "Shattered Lash",
    "Sheev",
    "Sibear",
    "Sigma & Octantis",
    "Silva & Aegis",
    "Silva & Aegis Prime",
    "Sirocco",
    "Skana",
    "Skana Prime",
    "Skiajati",
    "Slaytra",
    "Spinnerex",
    "Stropha",
    "Sun & Moon",
    "Syam",
    "Sydon",
    "Synoid Heliocor",
    "Tak & Lug",
    "Tatsu",
    "Tatsu Prime",
    "Tekko",
    "Tekko Prime",
    "Telos Boltace",
    "Tenet Agendus",
    "Tenet Exec",
    "Tenet Grigori",
    "Tenet Livia",
    "Thalys",
    "Tipedo",
    "Tipedo Prime",
    "Tonbo",
    "Tonkkatt",
    "Twin Basolk",
    "Twin Krohkur",
    "Valkyr Talons",
    "Vastilok",
    "Vaykor Sydon",
    "Venato",
    "Venato Prime",
    "Venka",
    "Venka Prime",
    "Verdilac",
    "Vericres",
    "Vinquibus (Melee)",
    "Vitrica",
    "Volnus",
    "Volnus Prime",
    "War",
    "War Prime",
    "Whipclaw",
    "Wolf Sledge",
    "Wrath",
    "Xoris",
    "Zenistar",
]

type UpgradeName = Literal[
    "Accelerated Blast",
    "Accelerated Isotope",
    "Acid Shells",
    "Adhesive Blast",
    "Aerial Ace",
    "Aero Agility",
    "Aero Periphery",
    "Agile Aim",
    "Air Recon",
    "Akimbo Slip Shot",
    "Amalgam Argonak Metal Auger",
    "Amalgam Barrel Diffusion",
    "Amalgam Daikyu Target Acquired",
    "Amalgam Furax Body Count",
    "Amalgam Javlok Magazine Warp",
    "Amalgam Organ Shatter",
    "Amalgam Ripkas True Steel",
    "Amalgam Serration",
    "Amalgam Shotgun Barrage",
    "Amanata Pressure",
    "Amar's Contempt",
    "Ambush Optics",
    "Ammo Chain",
    "Ammo Drum",
    "Ammo Stock",
    "Anemic Agility",
    "Apex Predator",
    "Arcane Acceleration",
    "Arcane Aegis",
    "Arcane Agility",
    "Arcane Arachne",
    "Arcane Avenger",
    "Arcane Awakening",
    "Arcane Barrier",
    "Arcane Battery",
    "Arcane Bellicose",
    "Arcane Blade Charger",
    "Arcane Blessing",
    "Arcane Bodyguard",
    "Arcane Camisado",
    "Arcane Circumvent",
    "Arcane Concentration",
    "Arcane Consequence",
    "Arcane Crepuscular",
    "Arcane Deflection",
    "Arcane Double Back",
    "Arcane Energize",
    "Arcane Eruption",
    "Arcane Escapist",
    "Arcane Expertise",
    "Arcane Fury",
    "Arcane Grace",
    "Arcane Guardian",
    "Arcane Healing",
    "Arcane Hot Shot",
    "Arcane Ice",
    "Arcane Ice Storm",
    "Arcane Impetus",
    "Arcane Intention",
    "Arcane Momentum",
    "Arcane Nullifier",
    "Arcane Persistence",
    "Arcane Phantasm",
    "Arcane Pistoleer",
    "Arcane Power Ramp",
    "Arcane Precision",
    "Arcane Primary Charger",
    "Arcane Pulse",
    "Arcane Rage",
    "Arcane Reaper",
    "Arcane Resistance",
    "Arcane Rise",
    "Arcane Sculptor",
    "Arcane Steadfast",
    "Arcane Strike",
    "Arcane Tanker",
    "Arcane Tempo",
    "Arcane Trickery",
    "Arcane Truculence",
    "Arcane Ultimatum",
    "Arcane Universal Fallout",
    "Arcane Velocity",
    "Arcane Victory",
    "Arcane Warmth",
    "Archgun Ace",
    "Argon Scope",
    "Arrow Mutation",
    "Astral Autopsy",
    "Astral Slash",
    "Atomic Fallout",
    "Auger Strike",
    "Augur Pact",
    "Augur Seeker",
    "Automatic Trigger",
    "Avenging Truth",
    "Ballista Measure",
    "Bane of Corpus",
    "Bane of Grineer",
    "Bane of Infested",
    "Bane of Orokin",
    "Bane of The Murmur",
    "Barrel Diffusion",
    "Bell Ringer",
    "Berserker Fury",
    "Bhisaj-Bal",
    "Biotic Rounds",
    "Bite",
    "Blade of Truth",
    "Bladed Rounds",
    "Blaze",
    "Blazing Steel",
    "Bleeding Edge",
    "Blind Shot",
    "Blood Rush",
    "Bloodthirst",
    "Blunderbuss",
    "Body Count",
    "Bore",
    "Boreal's Contempt",
    "Bounty Hunter",
    "Brain Storm",
    "Breach Loader",
    "Bright Purity",
    "Broad Eye",
    "Brute Conditioning",
    "Burdened Magazine",
    "Burning Claws",
    "Burning Hate",
    "Bursting Mass",
    "Buzz Kill",
    "Calculated Victory",
    "Cannonade",
    "Carnis Mandible",
    "Carnis Stinger",
    "Cascadia Accuracy",
    "Cascadia Empowered",
    "Cascadia Flare",
    "Cascadia Overcharge",
    "Catalyzer Link",
    "Cautious Shot",
    "Charged Bullets",
    "Charged Chamber",
    "Charged Shell",
    "Chilling Claws",
    "Chilling Grasp",
    "Chilling Reload",
    "Cleanse Corpus",
    "Cleanse Grineer",
    "Cleanse Infested",
    "Cleanse Orokin",
    "Cleanse The Murmur",
    "Clip Delegation",
    "Collision Force",
    "Combat Reload",
    "Combo Fury",
    "Combo Killer",
    "Combustion Beam",
    "Combustion Rounds",
    "Comet Blast",
    "Comet Rounds",
    "Concealed Explosives",
    "Concussion Rounds",
    "Condition Overload",
    "Condition's Perfection",
    "Conductive Blade",
    "Conjunction Voltage",
    "Contagious Spread",
    "Containment Breach",
    "Contamination Casing",
    "Continuous Misery",
    "Convulsion",
    "Corrupt Charge",
    "Counterbalance",
    "Counterweight",
    "Covert Lethality",
    "Crash Course",
    "Crash Shot",
    "Creeping Bullseye",
    "Critical Deceleration",
    "Critical Delay",
    "Critical Focus",
    "Critical Meltdown",
    "Critical Mutation",
    "Critical Precision",
    "Cryo Coating",
    "Cryo Rounds",
    "Cull the Weak",
    "Cutting Edge",
    "Da-Ren",
    "Damzav-Vati",
    "Deadly Efficiency",
    "Deadly Maneuvers",
    "Deadly Sequence",
    "Deep Freeze",
    "Deft Tempo",
    "Depleted Reload",
    "Directed Convergence",
    "Disabling Conditioning",
    "Disarming Purity",
    "Discipline's Merit",
    "Dispatch Overdrive",
    "Disruptor",
    "Dizzying Rounds",
    "Double Tap",
    "Double-Barrel Drift",
    "Draining Gloom",
    "Dreadful Killshot",
    "Dreamer's Wrath",
    "Drifting Contact",
    "Dual Rounds",
    "Eagle Eye",
    "Efficient Beams",
    "Eject Magazine",
    "Electrified Barrel",
    "Electromagnetic Shielding",
    "Embedded Catalyzer",
    "Emergent Aftermath",
    "Empazu-Shol",
    "Enduring Affliction",
    "Enduring Strike",
    "Energizing Shot",
    "Energy Channel",
    "Entropy Burst",
    "Entropy Detonation",
    "Entropy Flight",
    "Entropy Spike",
    "Eroding Blight",
    "Esti Vel-Ikha",
    "Eternal Eradicate",
    "Eternal Logistics",
    "Eternal Onslaught",
    "Evir-Ti",
    "Eximus Advantage",
    "Exodia Brave",
    "Exodia Contagion",
    "Exodia Epidemic",
    "Exodia Force",
    "Exodia Hunt",
    "Exodia Might",
    "Exodia Triumph",
    "Exodia Valor",
    "Expel Corpus",
    "Expel Grineer",
    "Expel Infested",
    "Expel Orokin",
    "Expel The Murmur",
    "Explosive Demise",
    "Exposing Harpoon",
    "Extend",
    "Fanged Fusillade",
    "Fass Canticle",
    "Fast Hands",
    "Fatal Acceleration",
    "Feathered Arrows",
    "Fever Strike",
    "Final Tap",
    "Finishing Touch",
    "Firestorm",
    "Flak Shot",
    "Flame Gland",
    "Flechette",
    "Flux Overdrive",
    "Focus Energy",
    "Focus Radon",
    "Focused Acceleration",
    "Focused Defense",
    "Fomorian Accelerant",
    "Fractalized Reset",
    "Frail Momentum",
    "Frigid Blast",
    "Frost Jaw",
    "Frostbite",
    "Full Capacity",
    "Full Contact",
    "Fulmination",
    "Furor",
    "Fury",
    "Galvanized Acceleration",
    "Galvanized Aptitude",
    "Galvanized Chamber",
    "Galvanized Crosshairs",
    "Galvanized Diffusion",
    "Galvanized Elementalist",
    "Galvanized Hell",
    "Galvanized Reflex",
    "Galvanized Savvy",
    "Galvanized Scope",
    "Galvanized Shot",
    "Galvanized Steel",
    "Gilded Truth",
    "Glacial Edge",
    "Gladiator Might",
    "Gladiator Rush",
    "Gladiator Vice",
    "Gleaming Blight",
    "Gorgon Frenzy",
    "Grinloked",
    "Guardian Derision",
    "Guided Ordnance",
    "Gun Glide",
    "Gunslinger",
    "Hammer Shot",
    "Harkonar Scope",
    "Hata-Satya",
    "Hawk Eye",
    "Hayan-Dabor",
    "Healing Return",
    "Heartseeker",
    "Heated Charge",
    "Heavy Caliber",
    "Heavy Trauma",
    "Heavy Warhead",
    "Hell's Chamber",
    "Hellfire",
    "Hemorrhage",
    "Higasa Serration",
    "High Voltage",
    "Hok-Kaal",
    "Hollow Point",
    "Hollowed Bullets",
    "Hornet Strike",
    "Hunter Munitions",
    "Hunter Synergy",
    "Hunter Track",
    "Hunter's Bonesaw",
    "Hush",
    "Hydraulic Barrel",
    "Hydraulic Chamber",
    "Hydraulic Crosshairs",
    "Hydraulic Gauge",
    "Hypothermic Shell",
    "Ice Storm",
    "Immunity Resistance",
    "Impaler Munitions",
    "Impenetrable Offense",
    "Incendiary Coat",
    "Infected Clip",
    "Infectious Injection",
    "Internal Bleeding",
    "Ion Infusion",
    "Jagged Edge",
    "Jahu Canticle",
    "Jolt",
    "Jugulus Barbs",
    "Jugulus Spines",
    "Justice Blades",
    "Kaal-zidi",
    "Khra Canticle",
    "Kill Switch",
    "Killing Blow",
    "Kinetic Ricochet",
    "Laser Sight",
    "Lashta-Vak",
    "Lasting Purity",
    "Lasting Sting",
    "Leaded Gas",
    "Lethal Momentum",
    "Lethal Torrent",
    "Lie In Wait",
    "Life Strike",
    "Lingering Torment",
    "Loaded Capacity",
    "Lock and Load",
    "Lohk Canticle",
    "Longbow Sharpshot",
    "Loose Chamber",
    "Loose Hatch",
    "Loose Magazine",
    "Lorun-Tash",
    "Lucky Shot",
    "Magazine Extension",
    "Magazine Warp",
    "Magma Chamber",
    "Magnetic Capacity",
    "Magnetic Claws",
    "Magnetic Might",
    "Magnetic Rush",
    "Magnetic Strafe",
    "Magnetic Strike",
    "Magnetic Welt",
    "Magnetized Core",
    "Magnetized Cycle",
    "Magnum Force",
    "Maim",
    "Maiming Strike",
    "Malignant Force",
    "Mark of the Beast",
    "Marked Target",
    "Martial Fury",
    "Master's Edge",
    "Maul",
    "Maximum Capacity",
    "Measured Burst",
    "Mecha Overdrive",
    "Melee Afflictions",
    "Melee Animosity",
    "Melee Assimilation",
    "Melee Careen",
    "Melee Crescendo",
    "Melee Doughty",
    "Melee Duplicate",
    "Melee Elementalist",
    "Melee Exposure",
    "Melee Fortification",
    "Melee Influence",
    "Melee Prowess",
    "Melee Retaliation",
    "Melee Vortex",
    "Mending Shot",
    "Mentor's Legacy",
    "Merciless Gunfight",
    "Metal Auger",
    "Metamorphic Magazine",
    "Metem-Erun",
    "Metem-Hakh",
    "Meteor Crash",
    "Meteor Munitions",
    "Meticulous Aim",
    "Modified Munitions",
    "Molt Augmented",
    "Molt Efficiency",
    "Molt Reconstruct",
    "Molt Vigor",
    "Molten Impact",
    "Momentary Pause",
    "Mortal Conduct",
    "Motus Impact",
    "Motus Setup",
    "Nano-Applicator",
    "Napalm Grenades",
    "Narrow Barrel",
    "Nebula Bore",
    "Necrophagic Vigor",
    "Netra Invocation",
    "Neutralizing Justice",
    "Night Stalker",
    "Nightwatch Napalm",
    "Nira's Contempt",
    "No Return",
    "North Wind",
    "Omn-Evi",
    "Opportunity's Reach",
    "Organ Shatter",
    "Overview",
    "Pain Points",
    "Parallax Scope",
    "Parry",
    "Pathogen Rounds",
    "Pax Bolt",
    "Pax Charge",
    "Pax Seeker",
    "Pax Soar",
    "Perpetual Agony",
    "Photon Overcharge",
    "Piercing Caliber",
    "Piercing Hit",
    "Pistol Acuity",
    "Pistol Ammo Mutation",
    "Pistol Elementalist",
    "Pistol Gambit",
    "Pistol Pestilence",
    "Plan B",
    "Point Blank",
    "Point Strike",
    "Poisonous Sting",
    "Polar Magazine",
    "Power Throw",
    "Precision Conditioning",
    "Precision Munition",
    "Precision Strike",
    "Pressure Point",
    "Pressurized Magazine",
    "Primary Acuity",
    "Primary Blight",
    "Primary Bulwark",
    "Primary Compression",
    "Primary Crux",
    "Primary Deadhead",
    "Primary Debilitate",
    "Primary Dexterity",
    "Primary Exhilarate",
    "Primary Frostbite",
    "Primary Merciless",
    "Primary Obstruct",
    "Primary Overcharge",
    "Primary Plated Round",
    "Primed Ammo Chain",
    "Primed Ammo Stock",
    "Primed Bane of Corpus",
    "Primed Bane of Grineer",
    "Primed Bane of Infested",
    "Primed Bane of Orokin",
    "Primed Bane of The Murmur",
    "Primed Chamber",
    "Primed Charged Shell",
    "Primed Chilling Grasp",
    "Primed Cleanse Corpus",
    "Primed Cleanse Grineer",
    "Primed Cleanse Infested",
    "Primed Cleanse Orokin",
    "Primed Cleanse The Murmur",
    "Primed Combustion Rounds",
    "Primed Convulsion",
    "Primed Counterbalance",
    "Primed Cryo Rounds",
    "Primed Deadly Efficiency",
    "Primed Dual Rounds",
    "Primed Expel Corpus",
    "Primed Expel Grineer",
    "Primed Expel Infested",
    "Primed Expel Orokin",
    "Primed Expel The Murmur",
    "Primed Fast Hands",
    "Primed Fever Strike",
    "Primed Firestorm",
    "Primed Fulmination",
    "Primed Fury",
    "Primed Heated Charge",
    "Primed Heavy Trauma",
    "Primed Magazine Warp",
    "Primed Pistol Ammo Mutation",
    "Primed Pistol Gambit",
    "Primed Point Blank",
    "Primed Pressure Point",
    "Primed Quickdraw",
    "Primed Ravage",
    "Primed Reach",
    "Primed Rifle Ammo Mutation",
    "Primed Rubedo-Lined Barrel",
    "Primed Shotgun Ammo Mutation",
    "Primed Shred",
    "Primed Slip Magazine",
    "Primed Smite Corpus",
    "Primed Smite Grineer",
    "Primed Smite Infested",
    "Primed Smite Orokin",
    "Primed Smite The Murmur",
    "Primed Stabilizer",
    "Primed Steady Hands",
    "Primed Tactical Pump",
    "Primed Target Cracker",
    "Primed Venomous Clip",
    "Prize Kill",
    "Proton Jet",
    "Proton Snap",
    "Pummel",
    "Quasar Drill",
    "Quick Reload",
    "Quick Return",
    "Quickdraw",
    "Quickening",
    "Radiated Reload",
    "Radon Claws",
    "Range Advantage",
    "Ravage",
    "Razor Munitions",
    "Razor Shot",
    "Reach",
    "Rebound",
    "Recover",
    "Recuperate",
    "Reflex Coil",
    "Reflex Draw",
    "Relentless Assault",
    "Relentless Combination",
    "Rending Strike",
    "Repeater Clip",
    "Residual Boils",
    "Residual Malodor",
    "Residual Shock",
    "Residual Viremia",
    "Resolute Focus",
    "Rifle Ammo Mutation",
    "Rifle Aptitude",
    "Rifle Elementalist",
    "Rift Strike",
    "Rime Rounds",
    "Ripper Rounds",
    "Ris Invocation",
    "Rubedo-Lined Barrel",
    "Ruinous Extension",
    "Rupture",
    "Sabot Rounds",
    "Sacrificial Pressure",
    "Sacrificial Steel",
    "Sawtooth Clip",
    "Saxum Spittle",
    "Saxum Thorax",
    "Scattered Justice",
    "Scattering Inferno",
    "Scorch",
    "Searing Steel",
    "Secondary Cryogenic",
    "Secondary Deadhead",
    "Secondary Dexterity",
    "Secondary Encumber",
    "Secondary Enervate",
    "Secondary Fortifier",
    "Secondary Irradiate",
    "Secondary Kinship",
    "Secondary Merciless",
    "Secondary Outburst",
    "Secondary Shiver",
    "Secondary Surge",
    "Secondary Wind",
    "Seeker",
    "Seeking Force",
    "Seeking Fury",
    "Seismic Wave",
    "Semi-Pistol Cannonade",
    "Semi-Rifle Cannonade",
    "Semi-Shotgun Cannonade",
    "Sentient Barrage",
    "Sentient Incision",
    "Sentient Surge",
    "Sepsis Claws",
    "Sequence Burn",
    "Serrated Edges",
    "Serrated Rounds",
    "Serration",
    "Sey-Taph",
    "Sharpened Blade",
    "Sharpened Bullets",
    "Sharpshooter",
    "Shattering Impact",
    "Shattering Justice",
    "Shell Compression",
    "Shell Rush",
    "Shell Shock",
    "Shivering Contagion",
    "Shock Collar",
    "Shocking Claws",
    "Shocking Touch",
    "Shotgun Ammo Mutation",
    "Shotgun Barrage",
    "Shotgun Elementalist",
    "Shotgun Savvy",
    "Shotgun Vendetta",
    "Shrapnel Rounds",
    "Shrapnel Shot",
    "Shred",
    "Shred Shot",
    "Shredder",
    "Sil-Tabol",
    "Silent Battery",
    "Sinister Reach",
    "Skull Shots",
    "Slip Magazine",
    "Smite Corpus",
    "Smite Grineer",
    "Smite Infested",
    "Smite Orokin",
    "Smite The Murmur",
    "Snap Shot",
    "Soaring Strike",
    "Soft Hands",
    "Spectral Serration",
    "Speed Trigger",
    "Split Chamber",
    "Split Flights",
    "Spoiled Strike",
    "Spontaneous Singularity",
    "Spring-Loaded Blade",
    "Spring-Loaded Broadhead",
    "Spring-Loaded Chamber",
    "Spry Sights",
    "Stabilizer",
    "Stand Ground",
    "Static Alacrity",
    "Static Discharge",
    "Steady Hands",
    "Stinging Truth",
    "Stockpiled Blight",
    "Stormbringer",
    "Strafing Slide",
    "Strain Fever",
    "Strain Infection",
    "Stunning Speed",
    "Sudden Impact",
    "Sudden Justice",
    "Sundering Strike",
    "Suppress",
    "Sure Shot",
    "Sweeping Serration",
    "Swipe",
    "Sword Alone",
    "Synth Charge",
    "Tactical Pump",
    "Tactical Reload",
    "Tainted Clip",
    "Tainted Mag",
    "Tainted Shell",
    "Talsek-An",
    "Target Acquired",
    "Target Cracker",
    "Targeting Subsystem",
    "Tek Gravity",
    "Tempered Blade",
    "Terminal Velocity",
    "Tether Grenades",
    "Theorem Contagion",
    "Theorem Demulcent",
    "Theorem Infection",
    "Thermagnetic Shells",
    "Thermite Rounds",
    "Thunderbolt",
    "Thundermiter",
    "Toxic Barrage",
    "Toxic Blight",
    "Toxic Sequence",
    "Trick Mag",
    "Triple Tap",
    "True Punishment",
    "True Steel",
    "Truth's Flame",
    "Twitch",
    "Ubri-Kaneph",
    "Ulashta-Shol",
    "Unseen Dread",
    "Vanquished Prey",
    "Velox Conclusion",
    "Venom Teeth",
    "Venomous Clip",
    "Vicious Frost",
    "Vicious Spread",
    "Vigilante Armaments",
    "Vigilante Fervor",
    "Vigilante Offense",
    "Vigilante Supplies",
    "Vik-Anam",
    "Vikla-Safor",
    "Vile Acceleration",
    "Vile Discharge",
    "Vile Precision",
    "Virtuos Forge",
    "Virtuos Fury",
    "Virtuos Ghost",
    "Virtuos Null",
    "Virtuos Shadow",
    "Virtuos Spike",
    "Virtuos Strike",
    "Virtuos Surge",
    "Virtuos Tempo",
    "Virtuos Trojan",
    "Virulent Scourge",
    "Vital Sense",
    "Volatile Quick Return",
    "Volatile Rebound",
    "Volatile Variant",
    "Volcanic Edge",
    "Voltage Sequence",
    "Voltaic Strike",
    "Vome Invocation",
    "Vulcan Blitz",
    "Weeping Wounds",
    "Whirlwind",
    "Wild Frenzy",
    "Wildfire",
    "Winds of Purity",
    "Xata Invocation",
    "Yar Dal",
    "Zazvat-Kar",
    "Zodiac Shred",
]
