from typing import Literal


type PrimaryName = Literal[
    "AX-52",
    "Acceltra",
    "Acceltra Prime",
    "Aeolak",
    "Afentis",
    "Afentis Prime",
    "Alternox",
    "Alternox Prime",
    "Ambassador",
    "Amprex",
    "Arbucep",
    "Arca Plasmor",
    "Argonak",
    "Arquebex",
    "Artax",
    "Artemis Bow",
    "Astilla",
    "Astilla Prime",
    "Attica",
    "Basmu",
    "Battacor",
    "Baza",
    "Baza Prime",
    "Boar",
    "Boar Prime",
    "Boltor",
    "Boltor Prime",
    "Braton",
    "Braton Prime",
    "Braton Vandal",
    "Bubonico",
    "Burston",
    "Burston Prime",
    "Buzlok",
    "Carmine Penta",
    "Catchmoon (Primary)",
    "Cedo",
    "Cedo Prime",
    "Cernos",
    "Cernos Prime",
    "Cinta",
    "Coda Bassocyst",
    "Coda Bubonico",
    "Coda Hema",
    "Coda Sporothrix",
    "Coda Synapse",
    "Convectrix",
    "Corinth",
    "Corinth Prime",
    "Cortege",
    "Corvas",
    "Corvas Prime",
    "Cryotra",
    "Cyngas",
    "Daikyu",
    "Daikyu Prime",
    "Dera",
    "Dera Vandal",
    "Deth Machine Rifle",
    "Deth Machine Rifle Prime",
    "Dex Sybaris",
    "Drakgoon",
    "Dread",
    "Dual Decurion",
    "EFV-5 Jupiter",
    "Enkaus",
    "Evensong",
    "Exergis",
    "Felarx",
    "Ferrox",
    "Fluctus",
    "Flux Rifle",
    "Fulmin",
    "Fulmin Prime",
    "Gaze (Primary)",
    "Glaxion",
    "Glaxion Vandal",
    "Gorgon",
    "Gorgon Wraith",
    "Gotva Prime",
    "Grakata",
    "Grattler",
    "Grinlok",
    "Haalvu",
    "Harpak",
    "Hek",
    "Helstrum",
    "Hema",
    "Higasa",
    "Hind",
    "Ignis",
    "Ignis Wraith",
    "Imperator",
    "Imperator Vandal",
    "Javlok",
    "Karak",
    "Karak Wraith",
    "Kohm",
    "Komorex",
    "Kuva Ayanga",
    "Kuva Bramma",
    "Kuva Chakkhurr",
    "Kuva Drakgoon",
    "Kuva Grattler",
    "Kuva Hek",
    "Kuva Hind",
    "Kuva Karak",
    "Kuva Kohm",
    "Kuva Ogris",
    "Kuva Quartakk",
    "Kuva Sobek",
    "Kuva Tonkor",
    "Kuva Zarr",
    "Lanka",
    "Larkspur",
    "Larkspur Prime",
    "Laser Rifle",
    "Latron",
    "Latron Prime",
    "Latron Wraith",
    "Lenz",
    "Lizzie",
    "MK1-Braton",
    "MK1-Paris",
    "MK1-Strun",
    "Mandonel",
    "Mausolon",
    "Miter",
    "Morgha",
    "Multron",
    "Mutalist Cernos",
    "Mutalist Quanta",
    "Nagantaka",
    "Nagantaka Prime",
    "Nataruk",
    "Neutralizer",
    "Ogris",
    "Opticor",
    "Opticor Vandal",
    "Panthera",
    "Panthera Prime",
    "Paracyst",
    "Paris",
    "Paris Prime",
    "Penta",
    "Perigale",
    "Perigale Prime",
    "Phaedra",
    "Phage",
    "Phantasma",
    "Phantasma Prime",
    "Phenmor",
    "Prime Laser Rifle",
    "Prisma Dual Decurions",
    "Prisma Gorgon",
    "Prisma Grakata",
    "Prisma Grinlok",
    "Prisma Lenz",
    "Prisma Tetra",
    "Proboscis Cernos",
    "Purgator 1",
    "Quanta",
    "Quanta Vandal",
    "Quartakk",
    "Quellor",
    "Rakta Cernos",
    "Rattleguts (Primary)",
    "Rauta",
    "Reconifex",
    "Rubico",
    "Rubico Prime",
    "Sancti Tigris",
    "Scourge",
    "Scourge Prime",
    "Secura Penta",
    "Shedu",
    "Simulor",
    "Snipetron",
    "Snipetron Vandal",
    "Sobek",
    "Soma",
    "Soma Prime",
    "Sporelacer (Primary)",
    "Sporothrix",
    "Stahlta",
    "Steflos",
    "Stinger",
    "Stradavar",
    "Stradavar Prime",
    "Strun",
    "Strun Prime",
    "Strun Wraith",
    "Supra",
    "Supra Vandal",
    "Sweeper",
    "Sweeper Prime",
    "Sybaris",
    "Sybaris Prime",
    "Synapse",
    "Synoid Simulor",
    "Tazicor",
    "Telos Boltor",
    "Tenet Arca Plasmor",
    "Tenet Envoy",
    "Tenet Ferrox",
    "Tenet Flux Rifle",
    "Tenet Glaxion",
    "Tenet Quanta",
    "Tenet Tetra",
    "Tenora",
    "Tenora Prime",
    "Tetra",
    "Thornbak",
    "Tiberon",
    "Tiberon Prime",
    "Tigris",
    "Tigris Prime",
    "Tombfinger (Primary)",
    "Tonkor",
    "Torid",
    "Trumna",
    "Trumna Prime",
    "Vadarya Prime",
    "Vaykor Hek",
    "Vectis",
    "Vectis Prime",
    "Veldt",
    "Velocitus",
    "Verglas",
    "Verglas Prime",
    "Vermisplicer (Primary)",
    "Vinquibus (Primary)",
    "Vulcax",
    "Vulkar",
    "Vulkar Wraith",
    "Vulklok",
    "Zarr",
    "Zenith",
    "Zhuge",
    "Zhuge Prime",
]

type SecondaryName = Literal[
    "Acrid",
    "Aegrit",
    "Afuris",
    "Afuris Prime",
    "Akarius",
    "Akarius Prime",
    "Akbolto",
    "Akbolto Prime",
    "Akbronco",
    "Akbronco Prime",
    "Akjagara",
    "Akjagara Prime",
    "Aklato",
    "Aklex",
    "Aklex Prime",
    "Akmagnus",
    "Akmagnus Prime",
    "Aksomati",
    "Aksomati Prime",
    "Akstiletto",
    "Akstiletto Prime",
    "Akvasto",
    "Akvasto Prime",
    "Akzani",
    "Angstrum",
    "Arca Scisco",
    "Athodai",
    "Athodai Prime",
    "Atomos",
    "Azima",
    "Balefire Charger",
    "Ballistica",
    "Ballistica Prime",
    "Bolto",
    "Brakk",
    "Bronco",
    "Bronco Prime",
    "Burst Laser",
    "Burst Laser Prime",
    "Cantare",
    "Castanas",
    "Catabolyst",
    "Catchmoon (Secondary)",
    "Cestra",
    "Coda Catabolyst",
    "Coda Pox",
    "Coda Tysis",
    "Cyanex",
    "Cycron",
    "Despair",
    "Detron",
    "Dex Furis",
    "Dex Pixia",
    "Dual Cestra",
    "Dual Coda Torxica",
    "Dual Toxocyst",
    "EFV-8 Mars",
    "Embolist",
    "Epitaph",
    "Epitaph Prime",
    "Euphona Prime",
    "Furis",
    "Fusilai",
    "Gammacor",
    "Gaze (Secondary)",
    "Glory",
    "Grimoire",
    "Hikou",
    "Hikou Prime",
    "Hystrix",
    "Hystrix Prime",
    "Knell",
    "Knell Prime",
    "Kohmak",
    "Kompressa",
    "Kompressa Prime",
    "Kraken",
    "Kulstar",
    "Kunai",
    "Kuva Brakk",
    "Kuva Kraken",
    "Kuva Nukor",
    "Kuva Seer",
    "Kuva Twin Stubbas",
    "Laetum",
    "Lato",
    "Lato Prime",
    "Lato Vandal",
    "Lex",
    "Lex Prime",
    "MK1-Furis",
    "MK1-Kunai",
    "Magnus",
    "Magnus Prime",
    "Mara Detron",
    "Marelok",
    "Noctua",
    "Nukor",
    "Ocucor",
    "Onos",
    "Pandero",
    "Pandero Prime",
    "Plinx",
    "Pox",
    "Prisma Angstrum",
    "Prisma Burst Laser",
    "Prisma Twin Gremlins",
    "Pyrana",
    "Pyrana Prime",
    "Quatz",
    "Rakta Ballistica",
    "Rattleguts (Secondary)",
    "Regulators",
    "Riot-848",
    "Sagek Prime",
    "Sancti Castanas",
    "Scyotid",
    "Secura Dual Cestra",
    "Seer",
    "Sepulcrum",
    "Sicarus",
    "Sicarus Prime",
    "Sonicor",
    "Spectra",
    "Spectra Vandal",
    "Spira",
    "Spira Prime",
    "Sporelacer (Secondary)",
    "Staticor",
    "Stubba",
    "Stug",
    "Synoid Gammacor",
    "Talons",
    "Telos Akbolto",
    "Tenet Cycron",
    "Tenet Detron",
    "Tenet Diplos",
    "Tenet Plinx",
    "Tenet Spirex",
    "Tombfinger (Secondary)",
    "Twin Grakatas",
    "Twin Gremlins",
    "Twin Kohmak",
    "Twin Rogga",
    "Twin Vipers",
    "Twin Vipers Wraith",
    "Tysis",
    "Vasto",
    "Vasto Prime",
    "Vaykor Marelok",
    "Velox",
    "Velox Prime",
    "Vermisplicer (Secondary)",
    "Vesper 77",
    "Viper",
    "Viper Wraith",
    "Zakti",
    "Zakti Prime",
    "Zylok",
    "Zylok Prime",
    "Zymos",
]

type MeleeName = Literal[
    "Ack & Brunt",
    "Akaten",
    "Amanata",
    "Amphis",
    "Anku",
    "Ankyros",
    "Ankyros Prime",
    "Arca Titron",
    "Argo & Vel",
    "Arum Spinosa",
    "Atterax",
    "Azothane",
    "Balla",
    "Batoten",
    "Bo",
    "Bo Prime",
    "Boltace",
    "Broken Scepter",
    "Broken War",
    "Cadus",
    "Cassowar",
    "Caustacyst",
    "Ceramic Dagger",
    "Cerata",
    "Ceti Lacera",
    "Cobra & Crane",
    "Cobra & Crane Prime",
    "Coda Caustacyst",
    "Coda Hirudo",
    "Coda Mire",
    "Coda Motovore",
    "Coda Pathocyst",
    "Corufell",
    "Cronus",
    "Cyath",
    "Dakra Prime",
    "Dark Dagger",
    "Dark Split-Sword",
    "Dark Sword",
    "Dehtat",
    "Desert Wind",
    "Destreza",
    "Destreza Prime",
    "Dex Dakra",
    "Dex Nikana",
    "Diwata",
    "Dokrahm",
    "Dorrclave",
    "Dragon Nikana",
    "Dual Cleavers",
    "Dual Ether",
    "Dual Heat Swords",
    "Dual Ichor",
    "Dual Kamas",
    "Dual Kamas Prime",
    "Dual Keres",
    "Dual Keres Prime",
    "Dual Raza",
    "Dual Skana",
    "Dual Viciss",
    "Dual Zoren",
    "Dual Zoren Prime",
    "Edun",
    "Ekhein",
    "Endura",
    "Ether Daggers",
    "Ether Reaper",
    "Ether Sword",
    "Exalted Blade",
    "Exalted Chromatic Blade",
    "Exalted Umbra Blade",
    "Exalted Umbra Chromatic Blade",
    "Falcor",
    "Fang",
    "Fang Prime",
    "Fragor",
    "Fragor Prime",
    "Furax",
    "Furax Wraith",
    "Galariak Prime",
    "Galatine",
    "Galatine Prime",
    "Galvacord",
    "Garuda Prime Talons",
    "Garuda Talons",
    "Gazal Machete",
    "Ghoulsaw",
    "Glaive",
    "Glaive Prime",
    "Gram",
    "Gram Prime",
    "Guandao",
    "Guandao Prime",
    "Gunsen",
    "Gunsen Prime",
    "Halikar",
    "Halikar Wraith",
    "Harmony",
    "Hate",
    "Heat Dagger",
    "Heat Sword",
    "Heliocor",
    "Hespar",
    "Hirudo",
    "Innodem",
    "Iron Staff",
    "Jat Kittag",
    "Jat Kusar",
    "Jaw Sword",
    "Kama",
    "Karyst",
    "Karyst Prime",
    "Keratinos",
    "Kesheg",
    "Kestrel",
    "Kestrel Prime",
    "Kogake",
    "Kogake Prime",
    "Korrudo",
    "Korumm",
    "Kreska",
    "Krohkur",
    "Kronen",
    "Kronen Prime",
    "Kronsh",
    "Kuva Ghoulsaw",
    "Kuva Shildeg",
    "Lacera",
    "Lacerten",
    "Landslide Fists",
    "Lecta",
    "Lesion",
    "MK1-Bo",
    "MK1-Furax",
    "Machete",
    "Machete Wraith",
    "Magistar",
    "Masseter",
    "Masseter Prime",
    "Mewan",
    "Mios",
    "Mire",
    "Nami Skyla",
    "Nami Skyla Prime",
    "Nami Solo",
    "Nepheri",
    "Nikana",
    "Nikana Prime",
    "Ninkondi",
    "Ninkondi Prime",
    "Obex",
    "Ohma",
    "Okina",
    "Okina Prime",
    "Ooltha",
    "Orthos",
    "Orthos Prime",
    "Orvius",
    "Pangolin Prime",
    "Pangolin Sword",
    "Paracesis",
    "Pathocyst",
    "Pennant",
    "Plague Keewar",
    "Plague Kripath",
    "Plasma Sword",
    "Praedos",
    "Pride",
    "Prisma Dual Cleavers",
    "Prisma Machete",
    "Prisma Obex",
    "Prisma Ohma",
    "Prisma Skana",
    "Prova",
    "Prova Vandal",
    "Pulmonars",
    "Pupacyst",
    "Quassus",
    "Quassus Prime",
    "Rabvee",
    "Rakta Dark Dagger",
    "Reaper Prime",
    "Redeemer",
    "Redeemer Prime",
    "Ripkas",
    "Rumblejack",
    "Ruvox",
    "Sampotes",
    "Sancti Magistar",
    "Sarofang",
    "Sarofang Prime",
    "Sarpa",
    "Scindo",
    "Scindo Prime",
    "Scoliac",
    "Secura Lecta",
    "Sepfahn",
    "Serro",
    "Shadow Claws",
    "Shadow Clones",
    "Shaku",
    "Shattered Lash",
    "Sheev",
    "Sibear",
    "Sigma & Octantis",
    "Silva & Aegis",
    "Silva & Aegis Prime",
    "Sirocco",
    "Skana",
    "Skana Prime",
    "Skiajati",
    "Slaytra",
    "Spinnerex",
    "Stropha",
    "Sun & Moon",
    "Syam",
    "Sydon",
    "Synoid Heliocor",
    "Tak & Lug",
    "Tatsu",
    "Tatsu Prime",
    "Tekko",
    "Tekko Prime",
    "Telos Boltace",
    "Tenet Agendus",
    "Tenet Exec",
    "Tenet Grigori",
    "Tenet Livia",
    "Thalys",
    "Tipedo",
    "Tipedo Prime",
    "Tonbo",
    "Tonkkatt",
    "Twin Basolk",
    "Twin Krohkur",
    "Valkyr Talons",
    "Vastilok",
    "Vaykor Sydon",
    "Venato",
    "Venato Prime",
    "Venka",
    "Venka Prime",
    "Verdilac",
    "Vericres",
    "Vinquibus (Melee)",
    "Vitrica",
    "Volnus",
    "Volnus Prime",
    "War",
    "War Prime",
    "Whipclaw",
    "Wolf Sledge",
    "Wrath",
    "Xoris",
    "Zenistar",
]

type UpgradeName = Literal[
    "Accelerated Blast",
    "Accelerated Isotope",
    "Acid Shells",
    "Adhesive Blast",
    "Aerial Ace",
    "Aero Agility",
    "Aero Periphery",
    "Agile Aim",
    "Air Recon",
    "Akimbo Slip Shot",
    "Amalgam Argonak Metal Auger",
    "Amalgam Barrel Diffusion",
    "Amalgam Daikyu Target Acquired",
    "Amalgam Furax Body Count",
    "Amalgam Javlok Magazine Warp",
    "Amalgam Organ Shatter",
    "Amalgam Ripkas True Steel",
    "Amalgam Serration",
    "Amalgam Shotgun Barrage",
    "Amanata Pressure",
    "Amar's Contempt",
    "Ambush Optics",
    "Ammo Chain",
    "Ammo Drum",
    "Ammo Stock",
    "Anemic Agility",
    "Apex Predator",
    "Archgun Ace",
    "Argent Scourge",
    "Argo & Vel",
    "Argon Scope",
    "Arrow Mutation",
    "Arum Spinosa",
    "Astral Autopsy",
    "Astral Slash",
    "Astral Twilight",
    "Atlantis Vulcan",
    "Atomic Fallout",
    "Auger Strike",
    "Augur Pact",
    "Augur Seeker",
    "Automatic Trigger",
    "Avenging Truth",
    "Azothane",
    "Ballista Measure",
    "Bane of Corpus",
    "Bane of Grineer",
    "Bane of Infested",
    "Bane of Orokin",
    "Bane of The Murmur",
    "Barrel Diffusion",
    "Bell Ringer",
    "Berserker Fury",
    "Bhisaj-Bal",
    "Biotic Rounds",
    "Bite",
    "Biting Piranha",
    "Blade of Truth",
    "Bladed Rounds",
    "Blaze",
    "Blazing Steel",
    "Bleeding Edge",
    "Bleeding Willow",
    "Blind Justice",
    "Blind Shot",
    "Blood Rush",
    "Bloodthirst",
    "Blunderbuss",
    "Body Count",
    "Bore",
    "Boreal's Contempt",
    "Bounty Hunter",
    "Brain Storm",
    "Breach Loader",
    "Bright Purity",
    "Broad Eye",
    "Brutal Tide",
    "Brute Conditioning",
    "Bullet Dance",
    "Burdened Magazine",
    "Burning Claws",
    "Burning Hate",
    "Burning Wasp",
    "Bursting Mass",
    "Butcher's Revelry",
    "Buzz Kill",
    "Calculated Victory",
    "Cannonade",
    "Carnis Mandible",
    "Carnis Stinger",
    "Carving Mantis",
    "Cascadia Accuracy",
    "Cascadia Empowered",
    "Cascadia Flare",
    "Cascadia Overcharge",
    "Catalyzer Link",
    "Caustacyst",
    "Cautious Shot",
    "Celestial Nightfall",
    "Charged Bullets",
    "Charged Chamber",
    "Charged Shell",
    "Chilling Claws",
    "Chilling Grasp",
    "Chilling Reload",
    "Clashing Forest",
    "Cleanse Corpus",
    "Cleanse Grineer",
    "Cleanse Infested",
    "Cleanse Orokin",
    "Cleanse The Murmur",
    "Cleaving Whirlwind",
    "Clip Delegation",
    "Cobra & Crane",
    "Coiling Viper",
    "Collision Force",
    "Combat Reload",
    "Combo Fury",
    "Combo Killer",
    "Combustion Beam",
    "Combustion Rounds",
    "Comet Blast",
    "Comet Rounds",
    "Concealed Explosives",
    "Concussion Rounds",
    "Condition Overload",
    "Condition's Perfection",
    "Conductive Blade",
    "Conjunction Voltage",
    "Contagious Spread",
    "Containment Breach",
    "Contamination Casing",
    "Continuous Misery",
    "Convulsion",
    "Corrupt Charge",
    "Counterbalance",
    "Counterweight",
    "Covert Lethality",
    "Crash Course",
    "Crash Shot",
    "Crashing Havoc",
    "Crashing Timber",
    "Creeping Bullseye",
    "Crimson Dervish",
    "Critical Deceleration",
    "Critical Delay",
    "Critical Focus",
    "Critical Meltdown",
    "Critical Mutation",
    "Critical Precision",
    "Crossing Snakes",
    "Crushing Ruin",
    "Cryo Coating",
    "Cryo Rounds",
    "Cull the Weak",
    "Cunning Aspect",
    "Cutting Edge",
    "Cyclone Kraken",
    "Damzav-Vati",
    "Deadly Efficiency",
    "Deadly Maneuvers",
    "Deadly Sequence",
    "Decisive Judgement",
    "Deep Freeze",
    "Defiled Snapdragon",
    "Deft Tempo",
    "Depleted Reload",
    "Desert Wind",
    "Directed Convergence",
    "Disabling Conditioning",
    "Disarming Purity",
    "Discipline's Merit",
    "Dispatch Overdrive",
    "Disruptor",
    "Dividing Blades",
    "Diwata",
    "Dizzying Rounds",
    "Double Tap",
    "Double-Barrel Drift",
    "Draining Gloom",
    "Dreadful Killshot",
    "Dreamer's Wrath",
    "Drifting Contact",
    "Dual Rounds",
    "Eagle Eye",
    "Edun",
    "Efficient Beams",
    "Eject Magazine",
    "Electrified Barrel",
    "Electromagnetic Shielding",
    "Eleventh Storm",
    "Embedded Catalyzer",
    "Emergent Aftermath",
    "Enduring Affliction",
    "Enduring Strike",
    "Energizing Shot",
    "Energy Channel",
    "Entropy Burst",
    "Entropy Detonation",
    "Entropy Flight",
    "Entropy Spike",
    "Eroding Blight",
    "Exalted Blade",
    "Exalted Chromatic Blade",
    "Exalted Umbra Blade",
    "Exalted Umbra Chromatic Blade",
    "Eximus Advantage",
    "Exodia Brave",
    "Exodia Contagion",
    "Exodia Epidemic",
    "Exodia Force",
    "Exodia Hunt",
    "Exodia Might",
    "Exodia Triumph",
    "Exodia Valor",
    "Expel Corpus",
    "Expel Grineer",
    "Expel Infested",
    "Expel Orokin",
    "Expel The Murmur",
    "Explosive Demise",
    "Exposing Harpoon",
    "Extend",
    "Fanged Fusillade",
    "Fass Canticle",
    "Fast Hands",
    "Fatal Acceleration",
    "Fateful Truth",
    "Feathered Arrows",
    "Fever Strike",
    "Final Harbinger",
    "Final Tap",
    "Finishing Touch",
    "Firestorm",
    "Flailing Branch",
    "Flak Shot",
    "Flame Gland",
    "Flechette",
    "Flux Overdrive",
    "Focus Energy",
    "Focus Radon",
    "Focused Acceleration",
    "Focused Defense",
    "Fomorian Accelerant",
    "Four Riders",
    "Fractalized Reset",
    "Fracturing Wind",
    "Frail Momentum",
    "Frigid Blast",
    "Frost Jaw",
    "Frostbite",
    "Full Capacity",
    "Full Contact",
    "Fulmination",
    "Furor",
    "Fury",
    "Gaia's Tragedy",
    "Galeforce Dawn",
    "Galvanized Acceleration",
    "Galvanized Aptitude",
    "Galvanized Chamber",
    "Galvanized Crosshairs",
    "Galvanized Diffusion",
    "Galvanized Elementalist",
    "Galvanized Hell",
    "Galvanized Reflex",
    "Galvanized Savvy",
    "Galvanized Scope",
    "Galvanized Shot",
    "Galvanized Steel",
    "Gemini Cross",
    "Gilded Truth",
    "Glacial Edge",
    "Gladiator Might",
    "Gladiator Rush",
    "Gladiator Vice",
    "Gleaming Blight",
    "Gleaming Talon",
    "Gnashing Payara",
    "Gorgon Frenzy",
    "Grim Fury",
    "Grinloked",
    "Guardian Derision",
    "Guided Ordnance",
    "Gun Glide",
    "Gunslinger",
    "Hammer Shot",
    "Harkonar Scope",
    "Harrowing Spire",
    "Hata-Satya",
    "Hawk Eye",
    "Healing Return",
    "Heartseeker",
    "Heated Charge",
    "Heavy Caliber",
    "Heavy Trauma",
    "Heavy Warhead",
    "Hell's Chamber",
    "Hellfire",
    "Hemorrhage",
    "Higasa Serration",
    "High Noon",
    "High Voltage",
    "Hollow Point",
    "Hollowed Bullets",
    "Homing Fang",
    "Hornet Strike",
    "Hunter Munitions",
    "Hunter Synergy",
    "Hunter Track",
    "Hunter's Bonesaw",
    "Hush",
    "Hydraulic Barrel",
    "Hydraulic Chamber",
    "Hydraulic Crosshairs",
    "Hydraulic Gauge",
    "Hypothermic Shell",
    "Hysteria",
    "Ice Storm",
    "Immunity Resistance",
    "Impaler Munitions",
    "Impenetrable Offense",
    "Incendiary Coat",
    "Infected Clip",
    "Infectious Injection",
    "Internal Bleeding",
    "Ion Infusion",
    "Iron Phoenix",
    "Iron Staff",
    "Jagged Edge",
    "Jahu Canticle",
    "Jat Kusar",
    "Jolt",
    "Jugulus Barbs",
    "Jugulus Spines",
    "Justice Blades",
    "Keratinos",
    "Khra Canticle",
    "Kill Switch",
    "Killing Blow",
    "Kinetic Ricochet",
    "Korumm",
    "Laser Sight",
    "Lashing Coil",
    "Last Herald",
    "Lasting Purity",
    "Lasting Sting",
    "Leaded Gas",
    "Lethal Momentum",
    "Lethal Torrent",
    "Lie In Wait",
    "Life Strike",
    "Lingering Torment",
    "Loaded Capacity",
    "Lock and Load",
    "Lohk Canticle",
    "Longbow Sharpshot",
    "Loose Chamber",
    "Loose Hatch",
    "Loose Magazine",
    "Lucky Shot",
    "Mafic Rain",
    "Magazine Extension",
    "Magazine Warp",
    "Magma Chamber",
    "Magnetic Capacity",
    "Magnetic Claws",
    "Magnetic Might",
    "Magnetic Rush",
    "Magnetic Strafe",
    "Magnetic Strike",
    "Magnetic Welt",
    "Magnetized Core",
    "Magnetized Cycle",
    "Magnum Force",
    "Maim",
    "Maiming Strike",
    "Malicious Raptor",
    "Malignant Force",
    "Mark of the Beast",
    "Marked Target",
    "Martial Fury",
    "Master's Edge",
    "Maul",
    "Maximum Capacity",
    "Measured Burst",
    "Mecha Overdrive",
    "Melee Afflictions",
    "Melee Animosity",
    "Melee Assimilation",
    "Melee Careen",
    "Melee Crescendo",
    "Melee Doughty",
    "Melee Duplicate",
    "Melee Elementalist",
    "Melee Exposure",
    "Melee Fortification",
    "Melee Influence",
    "Melee Prowess",
    "Melee Retaliation",
    "Melee Vortex",
    "Mending Shot",
    "Mentor's Legacy",
    "Merciless Gunfight",
    "Metal Auger",
    "Metamorphic Magazine",
    "Meteor Crash",
    "Meteor Munitions",
    "Meticulous Aim",
    "Modified Munitions",
    "Molten Impact",
    "Momentary Pause",
    "Mortal Conduct",
    "Motus Impact",
    "Motus Setup",
    "Mountain's Edge",
    "Nano-Applicator",
    "Napalm Grenades",
    "Narrow Barrel",
    "Nebula Bore",
    "Necrophagic Vigor",
    "Nepheri",
    "Netra Invocation",
    "Neutralizing Justice",
    "Night Stalker",
    "Nightwatch Napalm",
    "Nira's Contempt",
    "No Return",
    "Noble Cadence",
    "North Wind",
    "Opportunity's Reach",
    "Organ Shatter",
    "Overview",
    "Pain Points",
    "Parallax Scope",
    "Parry",
    "Pathogen Rounds",
    "Pax Bolt",
    "Pax Charge",
    "Pax Seeker",
    "Pax Soar",
    "Perpetual Agony",
    "Photon Overcharge",
    "Piercing Caliber",
    "Piercing Fury",
    "Piercing Hit",
    "Pistol Acuity",
    "Pistol Ammo Mutation",
    "Pistol Elementalist",
    "Pistol Gambit",
    "Pistol Pestilence",
    "Plan B",
    "Point Blank",
    "Point Strike",
    "Pointed Wind",
    "Poisonous Sting",
    "Polar Magazine",
    "Power Throw",
    "Precision Conditioning",
    "Precision Munition",
    "Precision Strike",
    "Pressure Point",
    "Pressurized Magazine",
    "Primal Fury",
    "Primary Acuity",
    "Primary Blight",
    "Primary Bulwark",
    "Primary Compression",
    "Primary Crux",
    "Primary Deadhead",
    "Primary Debilitate",
    "Primary Dexterity",
    "Primary Exhilarate",
    "Primary Frostbite",
    "Primary Merciless",
    "Primary Obstruct",
    "Primary Overcharge",
    "Primary Plated Round",
    "Primed Ammo Chain",
    "Primed Ammo Stock",
    "Primed Bane of Corpus",
    "Primed Bane of Grineer",
    "Primed Bane of Infested",
    "Primed Bane of Orokin",
    "Primed Bane of The Murmur",
    "Primed Chamber",
    "Primed Charged Shell",
    "Primed Chilling Grasp",
    "Primed Cleanse Corpus",
    "Primed Cleanse Grineer",
    "Primed Cleanse Infested",
    "Primed Cleanse Orokin",
    "Primed Cleanse The Murmur",
    "Primed Combustion Rounds",
    "Primed Convulsion",
    "Primed Counterbalance",
    "Primed Cryo Rounds",
    "Primed Deadly Efficiency",
    "Primed Dual Rounds",
    "Primed Expel Corpus",
    "Primed Expel Grineer",
    "Primed Expel Infested",
    "Primed Expel Orokin",
    "Primed Expel The Murmur",
    "Primed Fast Hands",
    "Primed Fever Strike",
    "Primed Firestorm",
    "Primed Fulmination",
    "Primed Fury",
    "Primed Heated Charge",
    "Primed Heavy Trauma",
    "Primed Magazine Warp",
    "Primed Pistol Ammo Mutation",
    "Primed Pistol Gambit",
    "Primed Point Blank",
    "Primed Pressure Point",
    "Primed Quickdraw",
    "Primed Ravage",
    "Primed Reach",
    "Primed Rifle Ammo Mutation",
    "Primed Rubedo-Lined Barrel",
    "Primed Shotgun Ammo Mutation",
    "Primed Shred",
    "Primed Slip Magazine",
    "Primed Smite Corpus",
    "Primed Smite Grineer",
    "Primed Smite Infested",
    "Primed Smite Orokin",
    "Primed Smite The Murmur",
    "Primed Stabilizer",
    "Primed Steady Hands",
    "Primed Tactical Pump",
    "Primed Target Cracker",
    "Primed Venomous Clip",
    "Prize Kill",
    "Proton Jet",
    "Proton Snap",
    "Pummel",
    "Quaking Hand",
    "Quasar Drill",
    "Quassus",
    "Quick Reload",
    "Quick Return",
    "Quickdraw",
    "Quickening",
    "Radiated Reload",
    "Radon Claws",
    "Range Advantage",
    "Ravage",
    "Razor Munitions",
    "Razor Shot",
    "Reach",
    "Reaping Spiral",
    "Rebound",
    "Recover",
    "Recuperate",
    "Reflex Coil",
    "Reflex Draw",
    "Relentless Assault",
    "Relentless Combination",
    "Rending Crane",
    "Rending Strike",
    "Rending Wind",
    "Repeater Clip",
    "Residual Boils",
    "Residual Malodor",
    "Residual Shock",
    "Residual Viremia",
    "Resolute Focus",
    "Rifle Ammo Mutation",
    "Rifle Aptitude",
    "Rifle Elementalist",
    "Rift Strike",
    "Rime Rounds",
    "Ripper Rounds",
    "Ris Invocation",
    "Rising Steel",
    "Rubedo-Lined Barrel",
    "Ruinous Extension",
    "Rupture",
    "Sabot Rounds",
    "Sacrificial Pressure",
    "Sacrificial Steel",
    "Sampotes",
    "Sawtooth Clip",
    "Saxum Spittle",
    "Saxum Thorax",
    "Scarlet Hurricane",
    "Scattered Justice",
    "Scattering Inferno",
    "Scorch",
    "Searing Steel",
    "Secondary Cryogenic",
    "Secondary Deadhead",
    "Secondary Dexterity",
    "Secondary Encumber",
    "Secondary Enervate",
    "Secondary Fortifier",
    "Secondary Irradiate",
    "Secondary Kinship",
    "Secondary Merciless",
    "Secondary Outburst",
    "Secondary Shiver",
    "Secondary Surge",
    "Secondary Wind",
    "Seeker",
    "Seeking Force",
    "Seeking Fury",
    "Seismic Palm",
    "Seismic Wave",
    "Semi-Pistol Cannonade",
    "Semi-Rifle Cannonade",
    "Semi-Shotgun Cannonade",
    "Sentient Barrage",
    "Sentient Incision",
    "Sentient Surge",
    "Sepsis Claws",
    "Sequence Burn",
    "Serene Storm",
    "Serrated Edges",
    "Serrated Rounds",
    "Serration",
    "Shadow Claws",
    "Shadow Harvest",
    "Sharpened Blade",
    "Sharpened Bullets",
    "Sharpshooter",
    "Shattering Impact",
    "Shattering Justice",
    "Shattering Storm",
    "Shell Compression",
    "Shell Rush",
    "Shell Shock",
    "Shimmering Blight",
    "Shivering Contagion",
    "Shock Collar",
    "Shocking Claws",
    "Shocking Touch",
    "Shotgun Ammo Mutation",
    "Shotgun Barrage",
    "Shotgun Elementalist",
    "Shotgun Savvy",
    "Shotgun Vendetta",
    "Shrapnel Rounds",
    "Shrapnel Shot",
    "Shred",
    "Shred Shot",
    "Shredder",
    "Sigma & Octantis",
    "Silent Battery",
    "Sinister Reach",
    "Sinking Talon",
    "Skull Shots",
    "Slicing Feathers",
    "Slip Magazine",
    "Smite Corpus",
    "Smite Grineer",
    "Smite Infested",
    "Smite Orokin",
    "Smite The Murmur",
    "Snap Shot",
    "Soaring Strike",
    "Soft Hands",
    "Sovereign Outcast",
    "Spectral Serration",
    "Speed Trigger",
    "Spinning Needle",
    "Split Chamber",
    "Split Flights",
    "Spoiled Strike",
    "Spontaneous Singularity",
    "Spring-Loaded Blade",
    "Spring-Loaded Broadhead",
    "Spring-Loaded Chamber",
    "Spry Sights",
    "Stabilizer",
    "Stalking Fan",
    "Stand Ground",
    "Star Divide",
    "Static Alacrity",
    "Static Discharge",
    "Steady Hands",
    "Stinging Thorn",
    "Stinging Truth",
    "Stockpiled Blight",
    "Stormbringer",
    "Strafing Slide",
    "Strain Fever",
    "Strain Infection",
    "Stunning Speed",
    "Sudden Impact",
    "Sudden Justice",
    "Sundering Strike",
    "Sundering Weave",
    "Suppress",
    "Sure Shot",
    "Sweeping Serration",
    "Swipe",
    "Swirling Tiger",
    "Swooping Falcon",
    "Sword Alone",
    "Syam",
    "Synth Charge",
    "Tactical Pump",
    "Tactical Reload",
    "Tainted Clip",
    "Tainted Hydra",
    "Tainted Mag",
    "Tainted Shell",
    "Target Acquired",
    "Target Cracker",
    "Targeting Subsystem",
    "Tatsu",
    "Tek Gravity",
    "Telos Boltace",
    "Tempered Blade",
    "Tempo Royale",
    "Tenet Agendus",
    "Tenet Exec",
    "Tenet Grigori",
    "Terminal Velocity",
    "Tether Grenades",
    "Thermagnetic Shells",
    "Thermite Rounds",
    "Thunderbolt",
    "Thundermiter",
    "Toxic Barrage",
    "Toxic Blight",
    "Toxic Sequence",
    "Tranquil Cleave",
    "Trick Mag",
    "Triple Tap",
    "True Punishment",
    "True Steel",
    "Truth's Flame",
    "Twirling Spire",
    "Twitch",
    "Unseen Dread",
    "Valkyr Talons",
    "Vanquished Prey",
    "Velox Conclusion",
    "Vengeful Revenant",
    "Venom Teeth",
    "Venomous Clip",
    "Verdilac",
    "Vermillion Storm",
    "Vicious Approach",
    "Vicious Frost",
    "Vicious Spread",
    "Vigilante Armaments",
    "Vigilante Fervor",
    "Vigilante Offense",
    "Vigilante Supplies",
    "Vile Acceleration",
    "Vile Discharge",
    "Vile Precision",
    "Virulent Scourge",
    "Vital Sense",
    "Vitrica",
    "Volatile Quick Return",
    "Volatile Rebound",
    "Volatile Variant",
    "Volcanic Edge",
    "Voltage Sequence",
    "Voltaic Strike",
    "Vome Invocation",
    "Votive Onslaught",
    "Vulcan Blitz",
    "Vulpine Mask",
    "Weeping Wounds",
    "Whirlwind",
    "Wild Frenzy",
    "Wildfire",
    "Winds of Purity",
    "Wise Razor",
    "Xata Invocation",
    "Zazvat-Kar",
    "Zenistar",
    "Zodiac Shred",
]

type EnemyName = Literal[
    "002-ER",
    "Aerial Commander",
    "Aerolyst",
    "Akkalak Turret",
    "Alad V",
    "Alpine Monitor Sawgaw",
    "Amalgam Alkonost",
    "Amalgam Arca Heqet",
    "Amalgam Arca Kucumatz",
    "Amalgam Cinder Machinist",
    "Amalgam Heqet",
    "Amalgam Kucumatz",
    "Amalgam MOA",
    "Amalgam Machinist",
    "Amalgam Osprey",
    "Amalgam Phase MOA",
    "Amalgam Satyr",
    "Amalgam Swarm Satyr",
    "Ambulas",
    "Amethyst Nexifera",
    "Ancient Disruptor",
    "Ancient Healer",
    "Ancient Protector",
    "Angst",
    "Anti MOA",
    "Anu Brachiolyst",
    "Anu Interference Drone",
    "Anu Mantalyst",
    "Anu Pyrolyst",
    "Anu Symbilyst",
    "Arbitration Shield Drone",
    "Arcane Boiler",
    "Archon Amar",
    "Archon Boreal",
    "Archon Nira",
    "Arid Butcher",
    "Arid Eviscerator",
    "Arid Heavy Gunner",
    "Arid Hellion",
    "Arid Lancer",
    "Arid Seeker",
    "Arid Trooper",
    "Armaments Director",
    "Armis Ulta",
    "Armored Roller",
    "Artificer",
    "Ashen Kuaka",
    "Attack Drone",
    "Attack Drone (Archwing Enemy)",
    "Attack Mutalist",
    "Auditor",
    "Aurax Actinic",
    "Aurax Atloc Raknoid",
    "Aurax Baculus",
    "Aurax Culveri MOA",
    "Aurax Polaris MOA",
    "Aurax Vertec",
    "Axio Basilisk",
    "Axio Crewman",
    "Axio Crewship",
    "Axio Detron Crewman",
    "Axio Disc MOA",
    "Axio Elite Crewman",
    "Axio Engineer",
    "Axio Gox",
    "Axio Harpi",
    "Axio MOA",
    "Axio Nullifier Crewman",
    "Axio Numon",
    "Axio Pilot",
    "Axio Railgun MOA",
    "Axio Ranger Crewman",
    "Axio Shield Osprey",
    "Axio Shockwave MOA",
    "Axio Stropha Crewman",
    "Axio Tech",
    "Axio Vambac",
    "Axio Weaver",
    "Axio Zerca",
    "Azoth",
    "Bailiff",
    "Ballista",
    "Basal Diploid",
    "Basal Diploid Rex",
    "Battalyst",
    "Bau Vasca Kavat",
    "Black-Banded Bolarola",
    "Blighted Maggot",
    "Blite Captain",
    "Boiler",
    "Bombard",
    "Brachiolyst",
    "Brindle Kubrodon",
    "Brood Mother",
    "Burrowing Cryptilex",
    "Butcher",
    "Buzzard Dropship",
    "Cannon Battery (Captain Vor)",
    "Cannon Battery (Corpus)",
    "Cannon Battery (Grineer)",
    "Captain Vor",
    "Carabus",
    "Carrier",
    "Carrion Charger",
    "Caustic Cryptilex",
    "Charger",
    "Choralyst",
    "Chroma",
    "Cinderthresh Hyena",
    "Clem",
    "Coastal Mergoo",
    "Coildrive",
    "Comet Shard",
    "Commander",
    "Common Avichaea",
    "Common Condroc",
    "Conculyst",
    "Condor Dropship",
    "Condor Dropship (Orb Vallis)",
    "Condor Storm Dropship",
    "Condrix",
    "Coolant Raknoid",
    "Corpus Cestra Target",
    "Corpus Power Carrier",
    "Corpus Power Carrier (Orb Vallis)",
    "Corpus Ramsled",
    "Corpus Sniper Target",
    "Corpus Supra Target",
    "Corpus Target",
    "Corpus Tech",
    "Corpus Trencher Target",
    "Corpus Warden",
    "Corrupted Ancient",
    "Corrupted Bombard",
    "Corrupted Butcher",
    "Corrupted Crewman",
    "Corrupted Drahk",
    "Corrupted Drahk Master",
    "Corrupted Drone",
    "Corrupted Heavy Gunner",
    "Corrupted Jackal",
    "Corrupted Lancer",
    "Corrupted MOA",
    "Corrupted Nullifier",
    "Corrupted Vor",
    "Corrupted Warden",
    "Corvette",
    "Councilor Vay Hek",
    "Crawler",
    "Crescent Vulpaphyla",
    "Crewman",
    "Dactolyst",
    "Dappled Horrasque",
    "Darek Draga",
    "Dargyn",
    "Dargyn Pilot",
    "Darvo",
    "Datalyst",
    "Dax Arcus",
    "Dax Equitem",
    "Dax Gladius",
    "Dax Herald",
    "Dax Malleus",
    "Death Scuttler",
    "Death Scuttlers",
    "Decaying Battalyst",
    "Decaying Conculyst",
    "Deep Archimedea Void Angel",
    "Deimos Ancient Healer",
    "Deimos Brood Mother",
    "Deimos Carnis",
    "Deimos Carnis Rex",
    "Deimos Charger",
    "Deimos Genetrix",
    "Deimos Juggernaut",
    "Deimos Jugulus",
    "Deimos Jugulus Rex",
    "Deimos Leaper",
    "Deimos Leaping Thrasher",
    "Deimos Mutalist Osprey Carrier",
    "Deimos Rogue Bonewidow",
    "Deimos Runner",
    "Deimos Saxum",
    "Deimos Saxum Rex",
    "Deimos Swarm Mutalist MOA",
    "Deimos Tendril Drone",
    "Deimos Therid",
    "Deimos Undying Flyer",
    "Deimos Venin Mutalist",
    "Delicate Pobber",
    "Demolisher Anti MOA",
    "Demolisher Bailiff",
    "Demolisher Boiler",
    "Demolisher Bonewidow",
    "Demolisher Bursa",
    "Demolisher Charger",
    "Demolisher Devourer",
    "Demolisher Expired",
    "Demolisher Heavy Gunner",
    "Demolisher Hyena",
    "Demolisher Juggernaut",
    "Demolisher Kuva Guardian",
    "Demolisher Machinist",
    "Demolisher Nox",
    "Demolisher Thrasher",
    "Demolisher Voidrig",
    "Demolyst",
    "Demolyst Heqet",
    "Demolyst MOA",
    "Demolyst Machinist",
    "Demolyst Osprey",
    "Demolyst Satyr",
    "Denial Bursa",
    "Derim Zahn",
    "Derivator Crewman",
    "Desert Skate",
    "Detron Crewman",
    "Devotee",
    "Disruptor Drone",
    "Draga",
    "Drahk",
    "Drahk Master",
    "Dreg",
    "Drekar Ballista",
    "Drekar Butcher",
    "Drekar Elite Lancer",
    "Drekar Eviscerator",
    "Drekar Heavy Gunner",
    "Drekar Hellion",
    "Drekar Lancer",
    "Drekar Manic",
    "Drekar Manic Bombard",
    "Drekar Scorpion",
    "Drekar Seeker",
    "Drekar Trooper",
    "Drover Bursa",
    "Dru Pesfor",
    "Drudge Brazer",
    "Drudge Foreman",
    "Drudge Scrapper",
    "Dusky-Headed Virmink",
    "Eclipse Thrax Centurion",
    "Eidolon Gantulyst",
    "Eidolon Hydrolyst",
    "Eidolon Lure",
    "Eidolon Teralyst",
    "Eidolon Vomvalyst",
    "Electric Crawler",
    "Elementa Arcocanid",
    "Elementa Culverin",
    "Elite Arid Lancer",
    "Elite Axio Basilisk",
    "Elite Axio Harpi",
    "Elite Axio Weaver",
    "Elite Crewman",
    "Elite Exo Cutter",
    "Elite Exo Flak",
    "Elite Exo Gokstad Crewship",
    "Elite Exo Outrider",
    "Elite Exo Taktis",
    "Elite Frontier Lancer",
    "Elite Gyre Cutter",
    "Elite Gyre Flak",
    "Elite Gyre Outrider",
    "Elite Gyre Taktis",
    "Elite Kosma Cutter",
    "Elite Kosma Flak",
    "Elite Kosma Outrider",
    "Elite Kosma Taktis",
    "Elite Lancer",
    "Elite Orm Basilisk",
    "Elite Orm Harpi",
    "Elite Orm Weaver",
    "Elite Shield Lancer",
    "Elite Taro Basilisk",
    "Elite Taro Harpi",
    "Elite Taro Weaver",
    "Elite Vorac Basilisk",
    "Elite Vorac Harpi",
    "Elite Vorac Weaver",
    "Ember Specter",
    "Emperor Condroc",
    "Equinox Specter",
    "Eradicyst",
    "Errant Specter",
    "Ethereal Void Angel",
    "Eviscerator",
    "Excalibur Specter",
    "Executioner Dhurnam",
    "Executioner Dok Thul",
    "Executioner Garesh",
    "Executioner Gorth",
    "Executioner Harkonar",
    "Executioner Nok",
    "Executioner Reth",
    "Executioner Vay Molta",
    "Executioner Zura",
    "Exo Butcher",
    "Exo Cutter",
    "Exo Elite Lancer",
    "Exo Eviscerator",
    "Exo Flak",
    "Exo Gokstad Crewship",
    "Exo Gokstad Officer",
    "Exo Gokstad Pilot",
    "Exo Outrider",
    "Exo Raider",
    "Exo Raider Carver",
    "Exo Raider Eviscerator",
    "Exo Ramsled",
    "Exo Roller Sentry",
    "Exo Supressor",
    "Exo Taktis",
    "Exploiter Orb",
    "Explosive Barrel",
    "Feral Diploid",
    "Feral Diploid Rex",
    "Feyarch Specter",
    "Fire-Veined Stover",
    "Flameblade",
    "Flossy Sawgaw",
    "Fog Comba",
    "Fog Scrambus",
    "Follie",
    "Fortress Scanner",
    "Frigate",
    "Frogmouthed Sawgaw",
    "Frontier Bailiff",
    "Frontier Butcher",
    "Frontier Eviscerator",
    "Frontier Heavy Gunner",
    "Frontier Hellion",
    "Frontier Lancer",
    "Frontier Regulator",
    "Frontier Seeker",
    "Frontier Trooper",
    "Frost Specter",
    "Frozen Infested Hive",
    "Fuming Dax Stover",
    "Fusion MOA",
    "Garv",
    "Gas Infested Hive",
    "General Sargas Ruk",
    "Ghost Kuaka",
    "Ghoul Auger",
    "Ghoul Auger Alpha",
    "Ghoul Devourer",
    "Ghoul Expired",
    "Ghoul Expired Deserter",
    "Ghoul Rictus",
    "Ghoul Rictus Alpha",
    "Ghoul Target",
    "Glacik Commander",
    "Gox",
    "Green Velocipod",
    "Grineer Manic",
    "Grineer Power Carrier",
    "Grineer Target",
    "Grineer Warden",
    "Gruzzling",
    "Guardsman",
    "Gyre Butcher",
    "Gyre Cutter",
    "Gyre Elite Lancer",
    "Gyre Eviscerator",
    "Gyre Flak",
    "Gyre Gokstad Crewship",
    "Gyre Gokstad Officer",
    "Gyre Gokstad Pilot",
    "Gyre Hyena",
    "Gyre Outrider",
    "Gyre Raider",
    "Gyre Raider Carver",
    "Gyre Raider Eviscerator",
    "Gyre Ramsled",
    "Gyre Roller Sentry",
    "Gyre Supressor",
    "Gyre Taktis",
    "Gyrix",
    "H-09 Apex",
    "H-09 Apex (Techrot)",
    "H-09 Efervon Tank",
    "H-09 Efervon Tank (Techrot)",
    "Hacked Drone",
    "Heavy Gunner",
    "Hellion",
    "Hellion Dargyn",
    "Hellion Power Carrier",
    "Hemocyte",
    "Hollow Thrax Centurion (Duviri)",
    "Hollow Thrax Centurion (Lua)",
    "Hollow Thrax Legatus (Duviri)",
    "Hollow Thrax Legatus (Lua)",
    "Horrasque Stormer",
    "Howler Undazoa",
    "Hunhullus",
    "Hurling Fragment",
    "Hyekka",
    "Hyekka Master",
    "Hyena LN2",
    "Hyena NG",
    "Hyena PB",
    "Hyena TH",
    "Icemire Hyena",
    "Infested Mesa",
    "Infested Oni",
    "Instigator Ghoul",
    "Ionyx",
    "Isolator Bursa",
    "J3 Jordas Golem",
    "Jack O'Naut",
    "Jackal",
    "Jad Teran",
    "Janus Captain Vor",
    "Jen Dro",
    "Jordas Golem",
    "Juggernaut",
    "Juggernaut Behemoth",
    "Juno Crewman",
    "Juno Dera MOA",
    "Juno Disc MOA",
    "Juno Elite Crewman",
    "Juno Fog Comba",
    "Juno Geminex MOA",
    "Juno Glaxion MOA",
    "Juno Jactus Osprey",
    "Juno Malleus Machinist",
    "Juno Nul Comba",
    "Juno Nullifier Crewman",
    "Juno Oxium Osprey",
    "Juno Sap Comba",
    "Juno Sapper MOA",
    "Juno Shield Osprey",
    "Juno Slo Comba",
    "Juno Sniper Crewman",
    "Juno Tech",
    "Kavat",
    "Kavor Defector",
    "Kela De Thaym",
    "Knave Specter",
    "Kosma Butcher",
    "Kosma Cutter",
    "Kosma Elite Lancer",
    "Kosma Eviscerator",
    "Kosma Flak",
    "Kosma Gokstad Crewship",
    "Kosma Gokstad Officer",
    "Kosma Gokstad Pilot",
    "Kosma Outrider",
    "Kosma Raider",
    "Kosma Raider Carver",
    "Kosma Raider Eviscerator",
    "Kosma Ramsled",
    "Kosma Roller Sentry",
    "Kosma Supressor",
    "Kosma Taktis",
    "Kubrodon Incarnadine",
    "Kubrow",
    "Kullervo (Boss)",
    "Kullervo (Descendia)",
    "Kuva Bailiff",
    "Kuva Ballista",
    "Kuva Bombard",
    "Kuva Butcher",
    "Kuva Dargyn",
    "Kuva Drahk",
    "Kuva Drahk Master",
    "Kuva Elite Lancer",
    "Kuva Eviscerator",
    "Kuva Flameblade",
    "Kuva Guardian",
    "Kuva Heavy Gunner",
    "Kuva Hellion",
    "Kuva Hyekka",
    "Kuva Hyekka Master",
    "Kuva Injector",
    "Kuva Jester",
    "Kuva Lancer",
    "Kuva Larvling",
    "Kuva Larvling (Female)",
    "Kuva Napalm",
    "Kuva Powerclaw",
    "Kuva Roller",
    "Kuva Scorch",
    "Kuva Scorpion",
    "Kuva Seeker",
    "Kuva Shield Lancer",
    "Kuva Siphon",
    "Kuva Trokarian",
    "Kuva Trooper",
    "Kyta Raknoid",
    "Lancer",
    "Lancer Dreg",
    "Lancer Survivor",
    "Lancing Infested Hive",
    "Latcher",
    "Latrox Une",
    "Leaper",
    "Leaping Thrasher",
    "Leech Osprey",
    "Leekter",
    "Legacyte",
    "Lektro Commander",
    "Lephantis",
    "Lieutenant Lech Kril",
    "Lobber Crawler",
    "Lockjaw & Sol",
    "Locust Drone",
    "Loki Specter",
    "Lua Thrax Legatus",
    "Lumbering Fragment",
    "Lynx",
    "Lynx Osprey",
    "Lynx Turret",
    "M-W.A.M.",
    "MOA",
    "Machinist",
    "Mag Specter",
    "Maggot",
    "Malice",
    "Mania",
    "Manic Bombard",
    "Medjay Predasite",
    "Mesa Specter",
    "Mimic",
    "Mine Osprey",
    "Minima MOA",
    "Misery",
    "Mite Raknoid",
    "Mitosid",
    "Mitosid Rex",
    "Mocking Whisper",
    "Mordda Turret",
    "Mutalist Alad V",
    "Mutalist Lightning Carrier",
    "Mutalist Osprey",
    "Mutalist Osprey Carrier",
    "Mutalist Toxic Carrier",
    "Nako Xol",
    "Napalm",
    "Narmer Ballista",
    "Narmer Bombard",
    "Narmer Buzzard Dropship",
    "Narmer Commander",
    "Narmer Condor Dropship",
    "Narmer Corpus Tech",
    "Narmer Crewman",
    "Narmer Deacon",
    "Narmer Dera MOA",
    "Narmer Detron Crewman",
    "Narmer Disc MOA",
    "Narmer Flameblade",
    "Narmer Geminex MOA",
    "Narmer Glaxion MOA",
    "Narmer Heavy Gunner",
    "Narmer Hellion",
    "Narmer Jailer",
    "Narmer Lancer",
    "Narmer Leech Osprey",
    "Narmer Militant",
    "Narmer Mine Osprey",
    "Narmer Napalm",
    "Narmer Nullifier Crewman",
    "Narmer Power Carrier (Orb Vallis)",
    "Narmer Powerfist",
    "Narmer Prod Crewman",
    "Narmer Raknoid",
    "Narmer Sapping Osprey",
    "Narmer Scorch",
    "Narmer Scorpion",
    "Narmer Shield Lancer",
    "Narmer Shield Osprey",
    "Narmer Sniper Crewman",
    "Narmer Thumper Doma",
    "Narmer Trooper",
    "Nauseous Crawler",
    "Necramite",
    "Necramite (Descendia)",
    "Nemes",
    "Nemes Ranger",
    "Nemes Rt",
    "Nemes Scout",
    "Nephil Vasca Kavat",
    "Nightwatch Bailiff",
    "Nightwatch Bombard",
    "Nightwatch Brunt Lancer",
    "Nightwatch Carrier",
    "Nightwatch Flameblade",
    "Nightwatch Gunner",
    "Nightwatch Hyekka Master",
    "Nightwatch Lancer",
    "Nightwatch Manic",
    "Nightwatch Powerclaw",
    "Nightwatch Reaver",
    "Nightwatch Seeker",
    "Nova Specter",
    "Nox",
    "Nul Comba",
    "Nul Scrambus",
    "Nullifier Crewman",
    "Nullifier Target",
    "Oculyst",
    "Ogma",
    "Optio",
    "Oraxia",
    "Oraxia (Descendia)",
    "Orbital Strike Drone",
    "Orm Basilisk",
    "Orm Crewman",
    "Orm Crewship",
    "Orm Detron Crewman",
    "Orm Disc MOA",
    "Orm Elite Crewman",
    "Orm Engineer",
    "Orm Gox",
    "Orm Harpi",
    "Orm MOA",
    "Orm Nullifier Crewman",
    "Orm Numon",
    "Orm Pilot",
    "Orm Railgun MOA",
    "Orm Ranger Crewman",
    "Orm Shield Osprey",
    "Orm Shockwave MOA",
    "Orm Stropha Crewman",
    "Orm Tech",
    "Orm Vambac",
    "Orm Weaver",
    "Orm Zerca",
    "Orokin Drone",
    "Orokin Sentry",
    "Orokin Spectator",
    "Orphid Specter",
    "Orphix",
    "Ortholyst",
    "Ostia Vasca Kavat",
    "Oxium Osprey",
    "Panzer Vulpaphyla",
    "Pelna Cade",
    "Penta Ranger",
    "Pharaoh Predasite",
    "Phorid",
    "Plains Commander",
    "Plains Kuaka",
    "Polyp-Hog Juggernaut",
    "Powerfist",
    "Prod Crewman",
    "Profit-Taker Orb",
    "Propaganda Drone",
    "Prosecutor",
    "Protea Specter",
    "Protector Stalker",
    "Pulsing Infested Hive",
    "Purple Velocipod",
    "Pyr Captain",
    "Quanta Ranger",
    "Rabbleback Hyena",
    "Railgun MOA",
    "Rana Del",
    "Ranger",
    "Raptor Mt",
    "Raptor Ns",
    "Raptor RX",
    "Raptor Rv",
    "Ratel",
    "Ravenous Void Angel",
    "Razorback",
    "Recon Commander",
    "Red-Crested Virmink",
    "Regulator",
    "Remech Osprey",
    "Rhino Specter",
    "Rogue Arcocanid",
    "Rogue Bonewidow",
    "Rogue Bonewidow (Descendia)",
    "Rogue Condroc",
    "Rogue Culverin",
    "Rogue Voidrig",
    "Rogue Voidrig (Deimos)",
    "Rogue Voidrig (Descendia)",
    "Roller",
    "Roller Sentry",
    "Ropalolyst",
    "Runner",
    "Rupturing Fragment",
    "Sap Comba",
    "Sap Scrambus",
    "Sapping Osprey",
    "Saryn Specter",
    "Saturn Six Fugitive",
    "Scaldra Barbican",
    "Scaldra Dedicant",
    "Scaldra Eradicator",
    "Scaldra Flayer",
    "Scaldra Harbinger",
    "Scaldra Jaeger",
    "Scaldra Screamer",
    "Scaldra TI-92",
    "Scarlet Nexifera",
    "Scathing Whisper",
    "Scavenger Drone",
    "Scorch",
    "Scorpion",
    "Scrofa Armaments Director",
    "Scrofa Attack Drone",
    "Scrofa Crewman",
    "Scrofa Decoy Moa",
    "Scrofa Demolition Director",
    "Scrofa Drover Bursa",
    "Scrofa Elite Crewman",
    "Scrofa Energy Chief",
    "Scrofa Grenadier Crewman",
    "Scrofa Heavy Trencher",
    "Scrofa Joro Raknoid",
    "Scrofa Laser Moa",
    "Scrofa Latro Raknoid",
    "Scrofa Legionary",
    "Scrofa Light Trencher",
    "Scrofa Lythrum Raknoid",
    "Scrofa Mine Osprey",
    "Scrofa Mite Raknoid",
    "Scrofa Obviator",
    "Scrofa Plasmor Crewman",
    "Scrofa Railgun Moa",
    "Scrofa Research Chief",
    "Scrofa Shield Osprey",
    "Scrofa Shockwave Moa",
    "Scrofa Sniper Ranger",
    "Scrofa Strike Director",
    "Scuttler",
    "Scuttlers",
    "Scyto Raknoid",
    "Security Camera",
    "Security Infested Hive",
    "Seeker",
    "Sensor Regulator",
    "Senta Turret (Corpus)",
    "Senta Turret (Kuva Fortress)",
    "Senta Turret (Orb Vallis)",
    "Sentient Research Director",
    "Sentinel Stover",
    "Septic Cryptilex",
    "Shadow Stalker",
    "Shield Dargyn",
    "Shield Lancer",
    "Shield Osprey",
    "Shield-Hellion Dargyn",
    "Shik Tal",
    "Shock Draga",
    "Shockwave MOA",
    "Shuffling Fragment",
    "Sikula",
    "Slo Comba",
    "Slo Scrambus",
    "Sly Vulpaphyla",
    "Sniper Crewman",
    "Specter Particles",
    "Spectralyst",
    "Splendid Mergoo",
    "Splintrix",
    "Sporule Avichaea",
    "Spotted Bolarola",
    "Sprag",
    "Stabilization Infested Hive",
    "Stalker",
    "Storage Container",
    "Subterranean Pobber",
    "Summulyst",
    "Sunny Pobber",
    "Swarm Mutalist MOA",
    "Swimmer Horrasque",
    "Symbilyst",
    "Syzygy Attack Drone",
    "Syzygy Denial Bursa",
    "Syzygy Light Trencher",
    "Syzygy Mite Raknoid",
    "Syzygy Prod Crewman",
    "Syzygy Shockwave Moa",
    "Syzygy Sniper Ranger",
    "Tar Mutalist MOA",
    "Tarask Bursa",
    "Taro Basilisk",
    "Taro Crewman",
    "Taro Crewship",
    "Taro Detron Crewman",
    "Taro Disc MOA",
    "Taro Elite Crewman",
    "Taro Engineer",
    "Taro Gox",
    "Taro Harpi",
    "Taro MOA",
    "Taro Nullifier Crewman",
    "Taro Numon",
    "Taro Pilot",
    "Taro Railgun MOA",
    "Taro Ranger Crewman",
    "Taro Secura Osprey",
    "Taro Shield Osprey",
    "Taro Shockwave MOA",
    "Taro Stropha Crewman",
    "Taro Tech",
    "Taro Vambac",
    "Taro Weaver",
    "Taro Zerca",
    "Techrot Babau",
    "Techrot Babau (Temporal Archimedea Survival)",
    "Techrot Galliflex",
    "Techrot Matmas",
    "Techrot Miasmite",
    "Techrot Obsolyte",
    "Techrot Ramsled",
    "Techrot Scaart",
    "Techrot Skuzzi",
    "Techrot Volatile Galliflex",
    "Temporal Dreg",
    "Terra Ambulas",
    "Terra Anti MOA",
    "Terra Attack Drone",
    "Terra Auto Turret",
    "Terra Crewman",
    "Terra Elite Crewman",
    "Terra Elite Embattor MOA",
    "Terra Elite Overtaker",
    "Terra Elite Provisor",
    "Terra Elite Raptor Sx",
    "Terra Elite Trencher",
    "Terra Embattor MOA",
    "Terra Jackal",
    "Terra Jailer",
    "Terra MOA",
    "Terra Manker",
    "Terra Overtaker",
    "Terra Oxium Osprey",
    "Terra Plasmor Crewman",
    "Terra Provisor",
    "Terra Railgun MOA",
    "Terra Raptor SX",
    "Terra Rocket Turret",
    "Terra Shield Osprey",
    "Terra Shockwave MOA",
    "Terra Sniper Crewman",
    "Terra Trencher",
    "The Anatomizer",
    "The Fragmented",
    "The Fragmented One",
    "The Hollow Vein",
    "The Raptor",
    "The Sergeant",
    "The Severed Warden",
    "The Unseeing Herald",
    "Thermic Raknoid",
    "Thorny Bolarola",
    "Thrax Centurion",
    "Thrax Legatus",
    "Tia Mayn",
    "Tomb Guardian",
    "Tomb Protector",
    "Tomb Protector Effigy",
    "Torment",
    "Toxic Ancient",
    "Toxic Crawler",
    "Treasurer",
    "Trinity Specter",
    "Trooper",
    "Trooper Survivor",
    "Tusk Ballista",
    "Tusk Bolkor",
    "Tusk Bombard",
    "Tusk Butcher",
    "Tusk Carabus",
    "Tusk Command Dargyn",
    "Tusk Dargyn",
    "Tusk Elite Lancer",
    "Tusk Eviscerator",
    "Tusk Firbolg",
    "Tusk Flameblade",
    "Tusk Heavy Gunner",
    "Tusk Hellion",
    "Tusk Lancer",
    "Tusk Mortar Bombard",
    "Tusk Napalm",
    "Tusk Ogma",
    "Tusk Predator",
    "Tusk Reaver",
    "Tusk Roller",
    "Tusk Seeker",
    "Tusk Seeker Drone",
    "Tusk Shield Dargyn",
    "Tusk Shield Lancer",
    "Tusk Target",
    "Tusk Thumper",
    "Tusk Thumper Bull",
    "Tusk Thumper Doma",
    "Tusk Trooper",
    "Tyl Regor",
    "Typholyst",
    "Tyro Battalyst",
    "Tyro Conculyst",
    "Umber Undazoa",
    "Undying Flyer",
    "Valkyr Specter",
    "Vallis Kubrodon",
    "Vallis Surveillance Drone",
    "Vaporous Undazoa",
    "Vapos Anti MOA",
    "Vapos Aquila",
    "Vapos Bioengineer",
    "Vapos Condor Dropship",
    "Vapos Condor Elite Dropship",
    "Vapos Crewman",
    "Vapos Detron Crewman",
    "Vapos Detron Ranger",
    "Vapos Elite Crewman",
    "Vapos Elite Ranger",
    "Vapos Fusion MOA",
    "Vapos MOA",
    "Vapos Nullifier",
    "Vapos Nullifier Ranger",
    "Vapos Oxium Osprey",
    "Vapos Prod Crewman",
    "Vapos Railgun MOA",
    "Vapos Ranger",
    "Vapos Sapping Osprey",
    "Vapos Shield Osprey",
    "Vapos Shockwave MOA",
    "Vapos Sniper Crewman",
    "Vapos Sniper Ranger",
    "Vapos Tech",
    "Vapos Tech Ranger",
    "Vay Hek Terra Frame",
    "Ved Xol",
    "Vem Tabook",
    "Ven'kra Tel",
    "Venin Mutalist",
    "Violence",
    "Viridian Nexifera",
    "Viscid Avichaea",
    "Vitriol Necramite",
    "Vivisect Director",
    "Vizier Predasite",
    "Void Angel",
    "Volatile Runner",
    "Volt Specter",
    "Vorac Basilisk",
    "Vorac Crewman",
    "Vorac Crewship",
    "Vorac Detron Crewman",
    "Vorac Disc MOA",
    "Vorac Elite Crewman",
    "Vorac Engineer",
    "Vorac Gox",
    "Vorac Harpi",
    "Vorac MOA",
    "Vorac Nullifier Crewman",
    "Vorac Numon",
    "Vorac Pilot",
    "Vorac Railgun MOA",
    "Vorac Ranger Crewman",
    "Vorac Shield Osprey",
    "Vorac Shockwave MOA",
    "Vorac Stropha Crewman",
    "Vorac Tech",
    "Vorac Vambac",
    "Vorac Weaver",
    "Vorac Zerca",
    "Vruush Turret",
    "White Velocipod",
    "White-Breasted Virmink",
    "Wolf of Saturn Six",
    "Woodland Mergoo",
    "Zanuka",
    "Zanuka Hunter",
    "Zealoid Bastion",
    "Zealoid Prelate",
    "Zealot Baptizer",
    "Zealot Herald",
    "Zealot Proselytizer",
    "Zeplen",
]
